### ISSUE TITLE
Documentation and example for the `KVM_SEV_LAUNCH_UPDATE_VMSA` call

### ISSUE THREAD

**Issue by viniul** [AMDESE/AMDSEV#104]
I am currently trying to implement running a VM in `AMD-SEV-ES` mode. This involves a call to the `KVM_SEV_LAUNCH_UPDATE_VMSA` function, according to the [SEV-ES specification ](https://www.amd.com/system/files/TechDocs/55766_SEV-KM_API_Specification.pdf). However, I can't find any further documentation about the `KVM_SEV_LAUNCH_UPDATE_VMSA` call (in particular, the [kernel documentation](https://www.kernel.org/doc/Documentation/virt/kvm/amd-memory-encryption.rst) only describes the case for AMD-SEV).

 The documentation is conflicting as well: While the SEV-ES specification states the `KVM_SEV_LAUNCH_UPDATE_VMSA` does take additional input, `qemu` uses the function without any further parameters, like so.
```
ret = sev_ioctl(sev->sev_fd, KVM_SEV_LAUNCH_UPDATE_VMSA, NULL, &fw_error);
```
see https://github.com/qemu/qemu/blob/27a985159a80430a0a43161797ca14ef946962b8/target/i386/sev.c#L788

Is there any documentation/example on how to use this call and also _when_ to use it (e.g., my intuition tells me it should be used after calling `KVM_SET_SREGS`?)

**Comment by tlendacky** [comment]
You have to remember that the SEV Specification and the KVM APIs exposed to userspace through the ioctl are not the same and may not align. The KVM_SEV_LAUNCH_UPDATE_VMSA ioctl will cause KVM to loop through each vCPU invoking the SEV LAUNCH_UPDATE_VMSA API for each VMSA associated with each vCPU. So in this case, no parameters are required from Qemu as KVM has all of the data.

See: https://github.com/torvalds/linux/blob/master/arch/x86/kvm/svm/sev.c#L644

This is done just before (and must be done before) the LAUNCH_MEASURE API is invoked, which finalizes the measurement.

**Comment by viniul** [comment]
Got it, thanks! And this has to be called _after_ `KVM_SET_SREGS`, correct? (Otherwise there is not VMSA block to encrypt, yes?)

**Comment by tlendacky** [comment]
It should be called after you have set the register state that you want set. The VMSA is allocated when the vCPU is created and the vCPU is created with some default register state (see https://github.com/torvalds/linux/blob/master/arch/x86/kvm/svm/svm.c#L1179). Before performing the LAUNCH_UPDATE_VMSA, this state is sync'd into the VMSA (see https://github.com/torvalds/linux/blob/master/arch/x86/kvm/svm/sev.c#L564). So there will be some values, but if you want to set specific values, then, yes, you should be calling KVM_SET_REGS/KVM_SET_SREGS as needed.

**Comment by viniul** [comment]
Managed to get it running, thanks -- closing this issue.
