### ISSUE TITLE
SEV-SNP: failed to INIT error 0x3 on a Dell Poweredge R6525 board (AMD Epyc 7453)

### ISSUE THREAD

**Issue by arkivm** [AMDESE/AMDSEV#107]
I am trying to boot an SEV-SNP enabled kernel on a node with AMD EPYC 7543 processor (Dell Poweredge R6525 board). I have upgraded the BIOS to the latest version (v2.8.4) and enabled all the recommended SEV options. However, SEV-SNP fails to initialize properly.

More details:
```
$ sev-tool --sys_info --verbose
-------------------------System Info-------------------------
Hostname: node-0
BIOS Version: 2.8.4
BIOS Release Date: 06/23/2022
SMT/Multi-Threading Status Per Socket:
CPU(s):                          128
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
Processor Frequency (all sockets):
2800 MHz
2800 MHz
Operating System: "Ubuntu 20.04 LTS"
Kernel Version: 5.19.0-rc6-snp-host-0aaa1e599bee
Git Commit #: Firmware Version:
Platform Family 0x19, Model 0x01
```

Here's the dmesg output on modprobe of ccp (dyn debug enabled)
```
[ 3979.985179] ccp 0000:22:00.1: no command queues available
[ 3979.985273] ccp 0000:22:00.1: registered SEV device
[ 3979.985275] ccp 0000:22:00.1: sev enabled
[ 3979.985276] ccp 0000:22:00.1: psp does not support TEE
[ 3979.985277] ccp 0000:22:00.1: psp enabled
[ 3979.985970] ccp 0000:a2:00.1: no command queues available
[ 3979.986016] ccp 0000:a2:00.1: psp does not support SEV
[ 3979.986019] ccp 0000:a2:00.1: psp does not support TEE
[ 3979.986021] ccp 0000:a2:00.1: psp enabled
[ 3979.986102] ccp 0000:22:00.1: sev command id 0x4 buffer 0x00000001549c4000 timeout 5s
[ 3979.986107] (in):  00000000: ffff ffff 0000 0000 0000 0000
[ 3979.986440] (out): 00000000: 3401 0000 0000 0400 0000 0000
[ 3979.986510] ccp 0000:22:00.1: sev command id 0xb buffer 0x00000001549c4000 timeout 100s
[ 3979.986512] (in):  00000000: 0020 5072 0001 0000 4300 0001
[ 3979.990430] ccp 0000:22:00.1: sev command 0xb failed (0x00000003)
[ 3979.990435] (out): 00000000: 0020 5072 0001 0000 4300 0001
[ 3979.990437] ccp 0000:22:00.1: Failed to update SEV firmware: 0x3
[ 3979.990466] ccp 0000:22:00.1: sev command id 0x81 buffer 0x0000000000000000 timeout 100s
[ 3980.042725] ccp 0000:22:00.1: sev command 0x81 failed (0x00000003)
[ 3980.042730] ccp 0000:22:00.1: SEV-SNP: failed to INIT error 0x3
[ 3980.048707] ccp 0000:22:00.1: sev command id 0x1 buffer 0x00000001549c4000 timeout 100s
[ 3980.048711] (in):  00000000: 0001 0000 0000 0000 0000 4ed0 0001 0000
[ 3980.048712] (in):  00000010: 0000 0010
[ 3980.084841] ccp 0000:22:00.1: sev command 0x1 failed (0x00000001)
[ 3980.084846] (out): 00000000: 0001 0000 0000 0000 0000 4ed0 0001 0000
[ 3980.084849] (out): 00000010: 0000 0010
[ 3980.084851] ccp 0000:22:00.1: SEV: failed to INIT error 0x1, rc -5
[ 3980.091035] ccp 0000:22:00.1: SEV API:1.52 build:4
```

I also tried updating the SEV firmware from https://developer.amd.com/sev/ for fam19. No luck.

**Comment by RARelph** [comment]
Your BIOS seems to have SEV/SNP FW version 1.52 build 4, which is the very latest available for Epyc 7xx3 parts, even newer than the 1.51.03 posted on https://developer.amd.com/sev/. I'm glad to see that Dell is keeping their BIOSes up to date. The driver shouldn't have tried to do the DOWNLOAD_FIRMWARE command (0xB), but the failure to update SEV FW is correct. The version installed is newer than the version provided through the command and that's an error.

The failure of the 0x81 SNP_INIT command is a problem. SNP_INIT has a lot of configuration checks and one of them is failing. The SNP specification describes them. You should be able to check them using commands like "rdmsr" to verify the contents of all the MSRs.

**Comment by tlendacky** [comment]
Since the level of the firmware is not advertised, the PSP/CCP driver will always try to do a DOWNLOAD_FIRMWARE command and rely on the firmware not downgrading itself.

Doesn't 1.52 require SNP_INIT_EX now? Ashish is working on that for the next release of the SNP hypervisor patches, so @arkivm  you may have to wait a bit for a branch update.

**Comment by arkivm** [comment]
Thank you @RARelph @tlendacky. I checked all the MSRs (except `DEBUG_STATUS`). It looks sane.

FWIW, I changed the `SEV_CMD_SNP_INIT` to `SEV_CMD_SNP_INIT_EX` and set `init_rmp` to 1 in the `__sev_snp_init_locked` function. For proper initialization, I am sure I need much more than that. So, this quick hack resulted in the same failure as I expected.

So, I will wait for the new host kernel version. Do you happen to know how long that would take @tlendacky?

**Comment by RARelph** [comment]
@arkivm Can you paste pictures of the BIOS settings you've changed? Or maybe provide a reference to the instructions you followed to change the BIOS settings.
The key ones are SMEE, MIN_SEV_ASID, RMP allocation, and IOHC/IOMMU SNP-enabled. I don't know what the Dell BIOS calls each of those, or what their default values are.
And just out of curiosity, could you provide the SYSCFG and RMP_BASE and RMP_END MSR values?
I think SNP_INIT ought to succeed if everything is as it should be.

**Comment by arkivm** [comment]
@RARelph The BIOS options for dell r6525 are listed [here](https://www.dell.com/support/manuals/en-us/poweredge-r6525/r6525_bios_ism_pub/processor-settings?guid=guid-ec36d324-4f45-4bc1-bb51-de2db7cc5cd9&lang=en-us)

Below are my settings:
```
SME - Enabled
Minimum SEV non-ES ASID - 8
SNP - Enabled
SNP Memory Coverage - Enabled
TSME - Disabled
```

Here are the MSRs
```
# SYSCFG
rdmsr 0xC0010010
3fc0000
# RMP_BASE
rdmsr 0xC0010132
15e00000
# RMP_END
rdmsr 0xC0010133
566fffff
```

**Comment by RARelph** [comment]
Looking at the Dell pages, I think you also need to set Kernel DMA Protection.

**Comment by arkivm** [comment]
I enabled the DMA protection. Unfortunately, that did not fix the issue.

**Comment by tlendacky** [comment]
> So, I will wait for the new host kernel version. Do you happen to know how long that would take @tlendacky?

Not off hand, but it shouldn't be too long.

**Comment by tlendacky** [comment]
Please try this branch: https://github.com/AMDESE/linux/tree/sev-snp-iommu-avic_5.19-rc6-snp-init-ex

**Comment by arkivm** [comment]
> Please try this branch: https://github.com/AMDESE/linux/tree/sev-snp-iommu-avic_5.19-rc6-snp-init-ex

Tried the new branch
```bash
$ uname -r
5.19.0-rc8-snp-host-d823c9ac7e51
```

No luck
```
[  399.215605] ccp 0000:22:00.1: no command queues available
[  399.215709] ccp 0000:22:00.1: registered SEV device
[  399.215710] ccp 0000:22:00.1: sev enabled
[  399.215711] ccp 0000:22:00.1: psp does not support TEE
[  399.215713] ccp 0000:22:00.1: psp enabled
[  399.216425] ccp 0000:a2:00.1: no command queues available
[  399.216474] ccp 0000:a2:00.1: psp does not support SEV
[  399.216476] ccp 0000:a2:00.1: psp does not support TEE
[  399.216479] ccp 0000:a2:00.1: psp enabled
[  399.216568] ccp 0000:22:00.1: sev command id 0x4 buffer 0x0000000111cde000 timeout 5s
[  399.216577] (in):  00000000: ffff ffff 0000 0000 0000 0000
[  399.216892] (out): 00000000: 3401 0000 0000 0400 0000 0000
[  399.216935] ccp 0000:22:00.1: No SEV firmware file present
[  399.217000] ccp 0000:22:00.1: sev command id 0x85 buffer 0x0000000111cde000 timeout 100s
[  399.217003] (in):  00000000: 0003 0000 0000 0000 7000 42f8 0001 0000
[  399.217004] (in):  00000010: 0000 0000 0000 0000 0000 0000 0000 0000
[  399.217005] (in):  00000020: 0000 0000 0000 0000 0000 0000 0000 0000
[  399.217006] (in):  00000030: 0000 0000 0000 0000 0000 0000 0000 0000
[  399.269608] ccp 0000:22:00.1: sev command 0x85 failed (0x00000003)
[  399.269614] (out): 00000000: 0003 0000 0000 0000 7000 42f8 0001 0000
[  399.269616] (out): 00000010: 0000 0000 0000 0000 0000 0000 0000 0000
[  399.269619] (out): 00000020: 0000 0000 0000 0000 0000 0000 0000 0000
[  399.269621] (out): 00000030: 0000 0000 0000 0000 0000 0000 0000 0000
[  399.269623] ccp 0000:22:00.1: SEV-SNP: failed to INIT error 0x3
[  399.275600] ccp 0000:22:00.1: sev command id 0x1 buffer 0x0000000111cde000 timeout 100s
[  399.275604] (in):  00000000: 0001 0000 0000 0000 0000 11d0 0001 0000
[  399.275605] (in):  00000010: 0000 0010
[  399.311988] ccp 0000:22:00.1: sev command 0x1 failed (0x00000001)
[  399.311993] (out): 00000000: 0001 0000 0000 0000 0000 11d0 0001 0000
[  399.311995] (out): 00000010: 0000 0010
[  399.311997] ccp 0000:22:00.1: SEV: failed to INIT error 0x1, rc -5
[  399.318189] ccp 0000:22:00.1: SEV API:1.52 build:4
```

* MSR and BIOS values are same as [before](https://github.com/AMDESE/AMDSEV/issues/107#issuecomment-1243215424) + KernelDMAProtection

**Comment by tlendacky** [comment]
Error 0x03 is INVALID_CONFIG (The platform configuration is invalid).

Did you enable the IOMMU SNP support in the BIOS?

**Comment by arkivm** [comment]
BIOS Processor settings
```
CcdCores=All
CcxAsNumaDomain=Disabled
CpuFeatureErms=Disabled
CpuFeatureFsrm=Disabled
CpuFeatureRmss=Disabled
CpuMinSevAsid=32
#IommuSupport=Enabled
KernelDmaProtection=Enabled
L1RegionPrefetcher=Enabled
L1StreamHwPrefetcher=Enabled
L1StridePrefetcher=Enabled
L2StreamHwPrefetcher=Enabled
L2UpDownPrefetcher=Enabled
LogicalProc=Enabled
MadtCoreEnumeration=Linear
NumaNodesPerSocket=1
#Proc1Brand=AMD EPYC 7543 32-Core Processor
#Proc1Id=19-1-1
#Proc1L2Cache=32x512 KB
#Proc1L3Cache=256 MB
#Proc1Microcode=0xA001173
#Proc1NumCores=32
#Proc2Brand=AMD EPYC 7543 32-Core Processor
#Proc2Id=19-1-1
#Proc2L2Cache=32x512 KB
#Proc2L3Cache=256 MB
#Proc2Microcode=0xA001173
#Proc2NumCores=32
#ProcBusSpeed=16 GT/s
ProcCcds=All
ProcConfigTdp=Maximum
#ProcCoreSpeed=2.80 GHz
ProcVirtualization=Enabled
ProcX2Apic=Enabled
Rmp=Enabled
Sme=Enabled
Snp=Enabled
TransparentSme=Disabled
```
Does this give any hint?
I do not see anything specific for SEV-SNP other than the generic IOMMU support.

**Comment by tlendacky** [comment]
I'm not sure. I've only ever verified it through the BIOS settings, specifically the AMD CBS options => NBIO options and ensured that SNP support was enabled.

**Comment by arkivm** [comment]
SEV-SNP [manual](https://www.amd.com/system/files/TechDocs/56860.pdf) pg.65 states that "The following MSRs must be set identically across all cores:"
* SYSCFG
* VM_HSAVE_PA
* DEBUG_STATUS (bit 2 and 7 must be 0)
* All MTRRs
* IORR_BASE
* IORR_MASK
* TOM
* TOM2

I could not figure out the address of `DEBUG_STATUS` MSR from the [manual](https://www.amd.com/system/files/TechDocs/24593.pdf). I checked `dr6` register though. However, bit 7 is reserved there.

I have the following MSR values (dumped from this [script](https://gist.github.com/arkivm/123eaed15848ac798de59375d4b93467)).

```
Name, address, set(values)
SYSCFG, 0xC0010010, {'3fc0000'}
IORRBase0, 0xC0010016, {'0'}
IORRMask0, 0xC0010019, {'0'}
IORRBase1, 0xC0010018, {'0'}
TOP_MEM, 0xC001001A, {'80000000'}
TOP_MEM2, 0xC001001D, {'4080000000'}
VM_HSAVE_PA, 0xC0010117, {'0'}
MTRRphysBase0, 0x200, {'ff000005'}
MTRRphysMask0, 0x201, {'ffffff000800'}
MTRRphysBase1, 0x202, {'6'}
MTRRphysMask1, 0x203, {'ffff80000800'}
MTRRphysBase2, 0x204, {'0'}
MTRRphysMask2, 0x205, {'0'}
MTRRphysBase3, 0x206, {'0'}
MTRRphysMask3, 0x207, {'0'}
MTRRphysBase4, 0x208, {'0'}
MTRRphysMask4, 0x209, {'0'}
MTRRphysBase5, 0x20a, {'0'}
MTRRphysMask5, 0x20b, {'0'}
MTRRphysBase6, 0x20c, {'0'}
MTRRphysMask6, 0x20d, {'0'}
MTRRphysBase7, 0x20e, {'0'}
MTRRphysMask7, 0x20f, {'0'}
MTRRfix64K_00000, 0x250, {'1e1e1e1e1e1e1e1e'}
MTRRfix16K_80000, 0x258, {'1e1e1e1e1e1e1e1e'}
MTRRfix16K_A0000, 0x259, {'0'}
MTRRfix4K_C0000, 0x268, {'1818181818181818'}
MTRRfix4K_C8000, 0x269, {'1d1d1d1d1d1d1d1d'}
MTRRfix4K_D0000, 0x26A, {'181818181d1d1d1d'}
MTRRfix4K_D8000, 0x26B, {'1818181818181818'}
MTRRfix4K_E0000, 0x26C, {'1818181818181818', '1010101010101010'}
MTRRfix4K_E8000, 0x26D, {'1010101018181818', '1818181818181818'}
MTRRfix4K_F0000, 0x26E, {'1818181818181818', '1010101010101010'}
MTRRfix4K_F8000, 0x26F, {'1818181818181818', '1010101010101010'}
MTRRdefType, 0x2FF, {'800'}
MTRRcap, 0x00FE, {'508'}
```

1) Could you please check if this looks correct? Also, on my setup, I have two different values for MSRs `0x26c..0x26f` (cpu0 has a different value, rest all cpus have the same). However, this violates the requirement _must be set identically across all cores_. Is this going to be a problem for successfully initializing `SNP_INIT_EX` command?

2) Also, could you post how these MSRs look on a working setup?

**Comment by tlendacky** [comment]
> 1. Also, on my setup, I have two different values for MSRs `0x26c..0x26f` (cpu0 has a different value, rest all cpus have the same). However, this violates the requirement _must be set identically across all cores_. Is this going to be a problem for successfully initializing `SNP_INIT_EX` command?

It seems like it would be a problem. The SEV firmware guys would know best, @RARelph?

**Comment by arkivm** [comment]
Thanks @tlendacky. Also, are these MSRs `0x26c..0x26f` writable? Also, I see these errors when I try to bring back all the CPUs on node 1 from offline->online. Does this give any hint?

```
...
[ 2630.119252] [Firmware Warn]: MTRR: CPU 0: SYSCFG[MtrrFixDramModEn] not cleared by BIOS, clearing this bit
[ 2630.128973] smpboot: Booting Node 1 Processor 127 APIC 0x7f
[ 2630.130932] [Firmware Warn]: MTRR: CPU 127: SYSCFG[MtrrFixDramModEn] not cleared by BIOS, clearing this bit
[ 2630.144806] MTRR: CPU 127: Writing MSR 26c to 10101010:10101010 failed
[ 2630.154766] MTRR: CPU 127: Writing MSR 26d to 18181818:10101010 failed
[ 2630.164725] MTRR: CPU 127: Writing MSR 26e to 10101010:10101010 failed
[ 2630.174683] MTRR: CPU 127: Writing MSR 26f to 10101010:10101010 failed
[ 2630.184705] microcode: CPU127: patch_level=0x0a00115d
...
```

Does SEV-SNP have any other restrictions, such as total memory, numa awareness, etc.?
The node I am trying on has 256 GiB of RAM, 2 x AMD EPYC 7543 32-core processor.

**Comment by RARelph** [comment]
Yes, the MTRRs and IORRs must be the same across all threads. These are usually configured by your BIOS.

**Comment by RARelph** [comment]
Name, address, set(values)
SYSCFG, 0xC0010010, {'3fc0000'}
IORRBase0, 0xC0010016, {'0'}
IORRMask0, 0xC0010019, {'0'}
IORRBase1, 0xC0010018, {'0'}
TOP_MEM, 0xC001001A, {'b0000000'}
TOP_MEM2, 0xC001001D, {'2050000000'}
VM_HSAVE_PA, 0xC0010117, {'0'}
MTRRphysBase0, 0x200, {'6'}
MTRRphysMask0, 0x201, {'ffff80000800'}
MTRRphysBase1, 0x202, {'80000006'}
MTRRphysMask1, 0x203, {'ffffe0000800'}
MTRRphysBase2, 0x204, {'a0000006'}
MTRRphysMask2, 0x205, {'fffff0000800'}
MTRRphysBase3, 0x206, {'a9e20000'}
MTRRphysMask3, 0x207, {'ffffffff0800'}
MTRRphysBase4, 0x208, {'0'}
MTRRphysMask4, 0x209, {'0'}
MTRRphysBase5, 0x20a, {'0'}
MTRRphysMask5, 0x20b, {'0'}
MTRRphysBase6, 0x20c, {'0'}
MTRRphysMask6, 0x20d, {'0'}
MTRRphysBase7, 0x20e, {'0'}
MTRRphysMask7, 0x20f, {'0'}
MTRRfix64K_00000, 0x250, {'1e1e1e1e1e1e1e1e'}
MTRRfix16K_80000, 0x258, {'1e1e1e1e1e1e1e1e'}
MTRRfix16K_A0000, 0x259, {'404040404040404'}
MTRRfix4K_C0000, 0x268, {'1515151515151515'}
MTRRfix4K_C8000, 0x269, {'1515151515151515'}
MTRRfix4K_D0000, 0x26A, {'1515151515151515'}
MTRRfix4K_D8000, 0x26B, {'1515151515151515'}
MTRRfix4K_E0000, 0x26C, {'1515151515151515'}
MTRRfix4K_E8000, 0x26D, {'1515151515151515'}
MTRRfix4K_F0000, 0x26E, {'1515151515151515'}
MTRRfix4K_F8000, 0x26F, {'1515151515151515'}
MTRRdefType, 0x2FF, {'c00'}
MTRRcap, 0x00FE, {'508'}

**Comment by arkivm** [comment]
Thanks for all the pointers @RARelph and @tlendacky. Apparently, the MSRs stay constant only when the BIOS.BootMode is set to UEFI on the host. After switching to UEFI, `SNP_INIT_EX` passes.
