### ISSUE TITLE
Does AMDSEV support shadow paging (npt=0)?

### ISSUE THREAD

**Issue by bvqbao** [AMDESE/AMDSEV#11]
Hello,

When I turned off nested page table (modprobe kvm_amd npt=0), the VM failed to boot.
I'm not sure if the current version of AMDSEV supports shadow paging (npt=0)?

Thanks,
Bao Bui

**Comment by jlarrew** [comment]
Hi Bao,

Nested Paging is required for SEV. If the guest chooses not to mark a page
encrypted in the guest page tables, then the hypervisor will have an
opportunity to encrypt the page using the hypervisor key by setting the
C-bit in the nested tables.

The hardware doesn't have any knowledge of shadow page tables, so they
can't be used to control memory encryption.

Sincerely,
Jesse

**Comment by bvqbao** [comment]
Thanks Jesse!
