### ISSUE TITLE
Failed to query the attestation report length ret=-22 fw_err=0 ()

### ISSUE THREAD

**Issue by alexander-lindner** [AMDESE/AMDSEV#111]
If I try to get an attestation report, I get this error message.
```json
{
 "error": {
   "class": "GenericError",
   "desc": "SEV: Failed to query the attestation report length ret=-22 fw_err=0 ()"
 }
}
```

I used this command:
```bash
echo '{ "execute": "qmp_capabilities" }\n{"execute":"query-sev-attestation-report","arguments":{"mnonce":"ZBaOEOsVmenc5q34VJb9jw=="}}' | socat - tcp:192.168.123.1:4444 | tail -1 | jq
```
What does this error message mean? Is this an intended message?

---------
Versions:
```
libvirt: 6.0.0-0ubuntu8.16
kernel: 5.4.0-125-generic
OS: Ubuntu 20.04.5 LTS
qemu-x86_64: 7.1.0
omvf: 0~20191122.bd85bf54-2ubuntu3.3
```
`sudo virsh domcapabilities | grep sev`
```xml
    <sev supported='yes'>
    </sev>
```

**Comment by tlendacky** [comment]
The support for getting the attestation report was added in the 5.12 kernel, so without a kernel at least at that level, you will receive the -EINVAL (-22) return code.

**Comment by alexander-lindner** [comment]
Indeed, after upgrading to Ubuntu 22.04 with kernel 5.15.0-48-generic it works quite fine.
