### ISSUE TITLE
Cannot enable SEV-ES or SEV-SNP

### ISSUE THREAD

**Issue by Daviiap** [AMDESE/AMDSEV#115]
I've followed the tutorial to build the kernel, but I can't enable SEV-ES or SEV-SNP.

When I run `dmesg | grep -i sev`, it returns:

```sh
[  108.484914] ccp 0000:42:00.1: sev enabled
[  108.535356] ccp 0000:42:00.1: SEV firmware update successful
[  108.567411] ccp 0000:42:00.1: SEV API:1.51 build:3
[  108.567417] ccp 0000:42:00.1: SEV API:1.51 build:3
[  108.677441] SEV supported: 509 ASIDs
```

But no SEV-SNP enabled...

There is any configuration to enable in the `GRUB_CMDLINE` like the `mem_encrypt=on` to enable SME feature?

I'm using a AMD EPYC MILAN (EPYC 7313)

**Comment by tlendacky** [comment]
Have you performed all the steps in the documentation regarding the BIOS settings? For SEV-ES, you'll need to increase the SEV-ES ASID allocation and for SEV-SNP there are other BIOS settings that need to be changed. Please refer to the README in the sev-snp-devel branch.

**Comment by Daviiap** [comment]
Is there any possibility to setup BIOS without rebooting the machine? I don't have physical access to the machine.

**Comment by tlendacky** [comment]
Doubtful...  If you have access to the system BMC, you could use that. That is how I access the BIOS screen.

**Comment by wdsun1008** [comment]
@Daviiap Did you solve this problem by modifying the BIOS settings?

**Comment by Daviiap** [comment]
Hi @wdsun1008! Yes, I had to update my BIOS to do it
