### ISSUE TITLE
kvm run failed Invalid argument

### ISSUE THREAD

**Issue by Daviiap** [AMDESE/AMDSEV#118]
I'm trying to run a SNP enabled guest following the steps in the sev-snp-devel branch, but i got this error:

```sh
error: kvm run failed Invalid argument
EAX=00000000 EBX=00000000 ECX=0000020f EDX=00000000
ESI=00000000 EDI=00000000 EBP=00000000 ESP=00000000
EIP=00000000 EFL=00000002 [-------] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0000 00000000 00000000 00000000
CS =0000 00000000 00000000 00000000
SS =0000 00000000 00000000 00000000
DS =0000 00000000 00000000 00000000
FS =0000 00000000 00000000 00000000
GS =0000 00000000 00000000 00000000
LDT=0000 00000000 00000000 00000000
TR =0000 00000000 00000000 00000000
GDT=     00000000 00000000
IDT=     00000000 00000000
CR0=80000001 CR2=00000000 CR3=00000000 CR4=00000020
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
EFER=0000000000000900
Code=<??> ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
```

**Comment by tlendacky** [comment]
Can you supply a bit more information:

- type of system
- uname -a
- generated qemu command line
- dmesg | egrep "ccp|SEV"
- is that all of the output you received?
- etc.

Anything that will help identify what the problem is.

**Comment by Daviiap** [comment]
AMD EPYC 7313, 62 G de RAM with Ubuntu 20.04.5 LTS;

uname -a return: `Linux securedsp 5.19.0-rc6-snp-host-cd1599797a25 #1 SMP PREEMPT_DYNAMIC Tue Oct 4 14:26:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

dmesg | egrep "ccp|SEV":
```sh
[   32.321010] SEV-SNP: RMP table physical address 0x0000000091300000 - 0x00000000a18fffff
[   86.944944] ccp 0000:42:00.1: no command queues available
[   86.945037] ccp 0000:42:00.1: sev enabled
[   86.945040] ccp 0000:42:00.1: psp enabled
[   86.994652] ccp 0000:42:00.1: SEV firmware update successful
[   87.937169] ccp 0000:42:00.1: SEV API:1.51 build:3
[   87.937177] ccp 0000:42:00.1: SEV-SNP API:1.51 build:3
[   87.943262] SEV supported: 410 ASIDs
[   87.943262] SEV-ES and SEV-SNP supported: 99 ASIDs
```

I'm running the following command: `./launch-qemu.sh -hda disk.qcow -sev-snp` and after some other info logs, got this error:

```sh
error: kvm run failed Invalid argument
EAX=00000000 EBX=00000000 ECX=0000020f EDX=00000000
ESI=00000000 EDI=00000000 EBP=00000000 ESP=00000000
EIP=00000000 EFL=00000002 [-------] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0000 00000000 00000000 00000000
CS =0000 00000000 00000000 00000000
SS =0000 00000000 00000000 00000000
DS =0000 00000000 00000000 00000000
FS =0000 00000000 00000000 00000000
GS =0000 00000000 00000000 00000000
LDT=0000 00000000 00000000 00000000
TR =0000 00000000 00000000 00000000
GDT=     00000000 00000000
IDT=     00000000 00000000
CR0=80000001 CR2=00000000 CR3=00000000 CR4=00000020
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
EFER=0000000000000900
Code=<??> ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
```

I'm able to run SEV and SEV-ES guests with no problem.

**Comment by tlendacky** [comment]
I've tried building everything and don't encounter an issue. Is there anything new in dmesg after the run fails? How far into the boot process does it get before this occurs? The other info logs might be important, if you can post the 40 or so odd lines before the failure that may help. Can you post the first few lines of the stdout.log file so I can also see the full qemu command used?

**Comment by Daviiap** [comment]
qemu command:

´´´sh
/home/ubuntu/AMDSEV/snp-release-2022-10-15/usr/local/bin/qemu-system-x86_64 -enable-kvm -cpu EPYC-v4 -machine q35 -smp 4,maxcpus=64 -m 2048M,slots=5,maxmem=30G -no-reboot -drive if=pflash,format=raw,unit=0,file=/home/ubuntu/AMDSEV/snp-release-2022-10-15/usr/local/share/qemu/OVMF_CODE.fd,readonly=on -drive if=pflash,format=raw,unit=1,file=/home/ubuntu/AMDSEV/snp-release-2022-10-15/root.fd -netdev user,id=vmnic  -device virtio-net-pci,disable-legacy=on,iommu_platform=true,netdev=vmnic,romfile= -drive file=/home/ubuntu/AMDSEV/snp-release-2022-10-15/root.qcow2,if=none,id=disk0,format=qcow2 -device virtio-scsi-pci,id=scsi0,disable-legacy=on,iommu_platform=true -device scsi-hd,drive=disk0 -machine memory-encryption=sev0,vmport=off -object sev-snp-guest,id=sev0,cbitpos=51,reduced-phys-bits=1 -nographic -monitor pty -monitor unix:monitor,server,nowait
´´´

The lines before the error occours:

´´´sh
[Bds]Booting UEFI QEMU QEMU HARDDISK 
 BlockSize : 512 
 LastBlock : 465FFF 
 Valid efi partition table header
 Valid efi partition table header
 Valid primary and Valid backup partition table
 Partition entries read block success
 Number of partition entries: 128
 start check partition entries
 End check partition entries
 Index : 0
 Start LBA : 37800
 End LBA : 465FDE
 Partition size: 42E7DF
 Start : 6F00000 End : 8CBFBC00
 Index : 13
 Start LBA : 800
 End LBA : 27FF
 Partition size: 2000
 Start : 100000 End : 4FFE00
 Index : 14
 Start LBA : 2800
 End LBA : 377FF
 Partition size: 35000
 Start : 500000 End : 6EFFE00
Prepare to Free Pool
 BlockSize : 512 
 LastBlock : 42E7DE 
 BlockSize : 512 
 LastBlock : 1FFF 
FSOpen: Open '\EFI\BOOT\BOOTX64.EFI' Success
[Bds] Expand PciRoot(0x0)/Pci(0x3,0x0)/Scsi(0x0,0x0) -> PciRoot(0x0)/Pci(0x3,0x0)/Scsi(0x0,0x0)/HD(15,GPT,265FBC03-3869-4314-B612-02BC15DD5043,0x2800,0x35000)/\EFI\BOOT\BOOTX64.EFI
BdsDxe: loading Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x3,0x0)/Scsi(0x0,0x0)
[Security] 3rd party image[0] can be loaded after EndOfDxe: PciRoot(0x0)/Pci(0x3,0x0)/Scsi(0x0,0x0)/HD(15,GPT,265FBC03-3869-4314-B612-02BC15DD5043,0x2800,0x35000)/\EFI\BOOT\BOOTX64.EFI.
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 7DFB6040
Loading driver at 0x0007D4F3000 EntryPoint=0x0007D515000 
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 7D7A4298
ProtectUefiImageCommon - 0x7DFB6040
  - 0x000000007D4F3000 - 0x00000000000D4000
BdsDxe: starting Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x3,0x0)/Scsi(0x0,0x0)
InstallProtocolInterface: 605DAB50-E046-4300-ABB6-3DD810DD8B23 7D5A2220
FSOpen: Open '\EFI\BOOT\fbx64.efi' Success
FSOpen: Open '\EFI\BOOT\fbx64.efi' Success
FSOpen: Open 'EFI' Success
FSOpen: Open 'ubuntu' Success
FSOpen: Open 'BOOTX64.CSV' Success
FSOpen: Open '\EFI\ubuntu\BOOTX64.CSV' Success
FSOpen: Open '\EFI\ubuntu\shimx64.efi' Success
[Security] 3rd party image[0] can be loaded after EndOfDxe: PciRoot(0x0)/Pci(0x3,0x0)/Scsi(0x0,0x0)/HD(15,GPT,265FBC03-3869-4314-B612-02BC15DD5043,0x2800,0x35000)/\EFI\ubuntu\shimx64.efi.
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 7D676040
Loading driver at 0x0007D335000 EntryPoint=0x0007D357000 
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 7D67C018
ProtectUefiImageCommon - 0x7D676040
  - 0x000000007D335000 - 0x00000000000D4000
[Variable]: Rewritten a preexisting variable(0x00000006) with different attributes(0x00000007) - 605DAB50-E046-4300-ABB6-3DD810DD8B23:MokListRT
[Variable]: Rewritten a preexisting variable(0x00000006) with different attributes(0x00000007) - 605DAB50-E046-4300-ABB6-3DD810DD8B23:MokListXRT
[Variable]: Rewritten a preexisting variable(0x00000006) with different attributes(0x00000007) - 605DAB50-E046-4300-ABB6-3DD810DD8B23:SbatLevelRT
InstallProtocolInterface: 605DAB50-E046-4300-ABB6-3DD810DD8B23 7D3E4220
FSOpen: Open '\EFI\ubuntu\grubx64.efi' Success
PixelBlueGreenRedReserved8BitPerColor
ConvertPages: range 1000000 - 3F71FFF covers multiple entries
ConvertPages: range 1000000 - 3F71FFF covers multiple entries
CpuDxe: 5-Level Paging = 0
MpInitChangeApLoopCallback() done!
SetUefiImageMemoryAttributes - 0x000000007F2E4000 - 0x0000000000009000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007F2DD000 - 0x0000000000007000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007F2D7000 - 0x0000000000006000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007F2D0000 - 0x0000000000007000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007F2C0000 - 0x0000000000010000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007F2BB000 - 0x0000000000005000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007F2B4000 - 0x0000000000007000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007F2B0000 - 0x0000000000004000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007F2AC000 - 0x0000000000004000 (0x0000000000000008)
error: kvm run failed Invalid argument
EAX=00000000 EBX=00000000 ECX=0000020f EDX=00000000
ESI=00000000 EDI=00000000 EBP=00000000 ESP=00000000
EIP=00000000 EFL=00000002 [-------] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0000 00000000 00000000 00000000
CS =0000 00000000 00000000 00000000
SS =0000 00000000 00000000 00000000
DS =0000 00000000 00000000 00000000
FS =0000 00000000 00000000 00000000
GS =0000 00000000 00000000 00000000
LDT=0000 00000000 00000000 00000000
TR =0000 00000000 00000000 00000000
GDT=     00000000 00000000
IDT=     00000000 00000000
CR0=80000001 CR2=00000000 CR3=00000000 CR4=00000020
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
EFER=0000000000000900
Code=<??> ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
´´´

**Comment by tlendacky** [comment]
> ```shell
> SetUefiImageMemoryAttributes - 0x000000007F2E4000 - 0x0000000000009000 (0x0000000000000008)
> SetUefiImageMemoryAttributes - 0x000000007F2DD000 - 0x0000000000007000 (0x0000000000000008)
> SetUefiImageMemoryAttributes - 0x000000007F2D7000 - 0x0000000000006000 (0x0000000000000008)
> SetUefiImageMemoryAttributes - 0x000000007F2D0000 - 0x0000000000007000 (0x0000000000000008)
> SetUefiImageMemoryAttributes - 0x000000007F2C0000 - 0x0000000000010000 (0x0000000000000008)
> SetUefiImageMemoryAttributes - 0x000000007F2BB000 - 0x0000000000005000 (0x0000000000000008)
> SetUefiImageMemoryAttributes - 0x000000007F2B4000 - 0x0000000000007000 (0x0000000000000008)
> SetUefiImageMemoryAttributes - 0x000000007F2B0000 - 0x0000000000004000 (0x0000000000000008)
> SetUefiImageMemoryAttributes - 0x000000007F2AC000 - 0x0000000000004000 (0x0000000000000008)
> error: kvm run failed Invalid argument
> ```

Ok, this helps. Your guest kernel is attempting to boot. However, I can't tell what guest kernel is booting as I didn't see the grub menu in your output. You may want to boot in non-SNP mode and disable the hidden grub menu boot and set a boot timeout value other than 0 (update /etc/default/grub), e.g:

- #GRUB_TIMEOUT_STYLE=hidden
- GRUB_TIMEOUT=10

While at it, be sure that "console=tty0 console=ttyS0,115200n8 earlyprintk=serial" are part of the default command line arguments, e.g.:

- GRUB_CMDLINE_LINUX_DEFAULT="console=tty0 console=ttyS1,115200n8 earlyprintk=serial"

I also typically add this in order to get grub on the serial console:

- GRUB_TERMINAL_INPUT="serial gfxterm"
- GRUB_TERMINAL_OUTPUT="serial gfxterm"
- GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=1 --word=8 --parity=no --stop=1"

And don't forget to run update-grub.

**Comment by Daviiap** [comment]
Made the changes, and this is the stdout.log final lines:

```sh
==AtaAtapiPassThru Start== Controller = 7E2BC798
InstallProtocolInterface: 1D3DE7F0-0807-424F-AA69-11A54E19A46F 7DE7C3C0
InstallProtocolInterface: 143B7632-B81B-4CB7-ABD3-B625A5B9BFFE 7DE7C410
InstallProtocolInterface: 19DF145A-B1D4-453F-8507-38816676D7F6 7D7CBB18
InstallProtocolInterface: 0167CCC4-D0F7-4F21-A3EF-9E64B7CDCE8B 7D7CBA20
 BlockSize : 512 
 LastBlock : 465FFF 
 Valid efi partition table header
 Valid efi partition table header
 Valid primary and Valid backup partition table
 Partition entries read block success
 Number of partition entries: 128
 start check partition entries
 End check partition entries
 Index : 0
 Start LBA : 37800
 End LBA : 465FDE
 Partition size: 42E7DF
 Start : 6F00000 End : 8CBFBC00
 Index : 13
 Start LBA : 800
 End LBA : 27FF
 Partition size: 2000
 Start : 100000 End : 4FFE00
 Index : 14
 Start LBA : 2800
 End LBA : 377FF
 Partition size: 35000
 Start : 500000 End : 6EFFE00
Prepare to Free Pool
 BlockSize : 512 
 LastBlock : 42E7DE 
 BlockSize : 512 
 LastBlock : 1FFF 
ClockRate = 1843200
Divisor   = 1
BaudRate/Actual (115200/115200) = 100%
PciSioSerial: Create SIO child serial device - Device Error
SataControllerStart START
SataControllerStart error return status = Already started
ClockRate = 1843200
Divisor   = 1
BaudRate/Actual (115200/115200) = 100%
PciSioSerial: Create SIO child serial device - Device Error
Select Item: 0x19
[Bds]OsIndication: 0000000000000000
[Bds]=============Begin Load Options Dumping ...=============
  Driver Options:
  SysPrep Options:
  Boot Options:
    Boot0004: ubuntu 		 0x0001
    Boot0000: UiApp 		 0x0109
    Boot0001: UEFI QEMU QEMU HARDDISK  		 0x0001
    Boot0002: UEFI PXEv4 (MAC:525400123456) 		 0x0001
    Boot0003: EFI Internal Shell 		 0x0001
  PlatformRecovery Options:
    PlatformRecovery0000: Default PlatformRecovery 		 0x0001
[Bds]=============End Load Options Dumping=============
[Bds]BdsWait ...Zzzzzzzzzzzz...
[Bds]Exit the waiting!
[Bds]Stop Hotkey Service!
[Bds]UnregisterKeyNotify: 000C/0000 Success
[Bds]UnregisterKeyNotify: 0017/0000 Success
[Bds]UnregisterKeyNotify: 0000/000D Success
Memory  Previous  Current    Next   
 Type    Pages     Pages     Pages  
======  ========  ========  ========
  0A    00000080  00000022  00000080
  09    00000012  0000000D  00000012
  00    00000080  00000030  00000080
  05    00000100  00000041  00000100
  06    00000100  000000B1  00000100
[Bds]Booting ubuntu
FSOpen: Open '\EFI\ubuntu\shimx64.efi' Success
[Bds] Expand HD(15,GPT,265FBC03-3869-4314-B612-02BC15DD5043,0x2800,0x35000)/\EFI\ubuntu\shimx64.efi -> PciRoot(0x0)/Pci(0x3,0x0)/Scsi(0x0,0x0)/HD(15,GPT,265FBC03-3869-4314-B612-02BC15DD5043,0x2800,0x35000)/\EFI\ubuntu\shimx64.efi
BdsDxe: loading Boot0004 "ubuntu" from HD(15,GPT,265FBC03-3869-4314-B612-02BC15DD5043,0x2800,0x35000)/\EFI\ubuntu\shimx64.efi
[Security] 3rd party image[0] can be loaded after EndOfDxe: PciRoot(0x0)/Pci(0x3,0x0)/Scsi(0x0,0x0)/HD(15,GPT,265FBC03-3869-4314-B612-02BC15DD5043,0x2800,0x35000)/\EFI\ubuntu\shimx64.efi.
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 7DFDB040
Loading driver at 0x0007D4F3000 EntryPoint=0x0007D515000 
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 7E2B7E98
ProtectUefiImageCommon - 0x7DFDB040
  - 0x000000007D4F3000 - 0x00000000000D4000
BdsDxe: starting Boot0004 "ubuntu" from HD(15,GPT,265FBC03-3869-4314-B612-02BC15DD5043,0x2800,0x35000)/\EFI\ubuntu\shimx64.efi
InstallProtocolInterface: 605DAB50-E046-4300-ABB6-3DD810DD8B23 7D5A2220
FSOpen: Open '\EFI\ubuntu\grubx64.efi' Success
PixelBlueGreenRedReserved8BitPerColor
ConvertPages: range 1000000 - 3F71FFF covers multiple entries
ConvertPages: range 1000000 - 3F71FFF covers multiple entries
CpuDxe: 5-Level Paging = 0
MpInitChangeApLoopCallback() done!
SetUefiImageMemoryAttributes - 0x000000007F2E4000 - 0x0000000000009000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007F2DD000 - 0x0000000000007000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007F2D7000 - 0x0000000000006000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007F2D0000 - 0x0000000000007000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007F2C0000 - 0x0000000000010000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007F2BB000 - 0x0000000000005000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007F2B4000 - 0x0000000000007000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007F2B0000 - 0x0000000000004000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007F2AC000 - 0x0000000000004000 (0x0000000000000008)
error: kvm run failed Invalid argument
EAX=00000000 EBX=00000000 ECX=0000020f EDX=00000000
ESI=00000000 EDI=00000000 EBP=00000000 ESP=00000000
EIP=00000000 EFL=00000002 [-------] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0000 00000000 00000000 00000000
CS =0000 00000000 00000000 00000000
SS =0000 00000000 00000000 00000000
DS =0000 00000000 00000000 00000000
FS =0000 00000000 00000000 00000000
GS =0000 00000000 00000000 00000000
LDT=0000 00000000 00000000 00000000
TR =0000 00000000 00000000 00000000
GDT=     00000000 00000000
IDT=     00000000 00000000
CR0=80000001 CR2=00000000 CR3=00000000 CR4=00000020
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
EFER=0000000000000900
Code=<??> ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ??
```

**Comment by tlendacky** [comment]
Please verify the guest kernel that you are attempting to boot, what is the name of the entry?. Additionally, please supply the last few lines of dmesg after this failure, e.g.: dmesg | tail -40

**Comment by Daviiap** [comment]
The -kernel is `/home/ubuntu/work/AMDSEV/snp-release-2022-10-17/linux/guest/linux-image-5.19.0-rc6-snp-guest-d9bd54fea4d2_5.19.0-rc6-snp-guest-d9bd54fea4d2-1_amd64.deb`

dmesg | tail -40:

```
[   91.737666] rdac: device handler registered
[   92.010508] loop0: detected capacity change from 0 to 129480
[   92.098212] loop1: detected capacity change from 0 to 138880
[   92.173976] loop2: detected capacity change from 0 to 98272
[   93.075194] audit: type=1400 audit(1666029640.915:2): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lsb_release" pid=1092 comm="apparmor_parser"
[   93.075654] audit: type=1400 audit(1666029640.915:3): apparmor="STATUS" operation="profile_load" profile="unconfined" name="nvidia_modprobe" pid=1087 comm="apparmor_parser"
[   93.075660] audit: type=1400 audit(1666029640.915:4): apparmor="STATUS" operation="profile_load" profile="unconfined" name="nvidia_modprobe//kmod" pid=1087 comm="apparmor_parser"
[   93.076058] audit: type=1400 audit(1666029640.919:5): apparmor="STATUS" operation="profile_load" profile="unconfined" name="libvirtd" pid=1088 comm="apparmor_parser"
[   93.076061] audit: type=1400 audit(1666029640.919:6): apparmor="STATUS" operation="profile_load" profile="unconfined" name="libvirtd//qemu_bridge_helper" pid=1088 comm="apparmor_parser"
[   93.076172] audit: type=1400 audit(1666029640.919:7): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/bin/man" pid=1089 comm="apparmor_parser"
[   93.076176] audit: type=1400 audit(1666029640.919:8): apparmor="STATUS" operation="profile_load" profile="unconfined" name="man_filter" pid=1089 comm="apparmor_parser"
[   93.076178] audit: type=1400 audit(1666029640.919:9): apparmor="STATUS" operation="profile_load" profile="unconfined" name="man_groff" pid=1089 comm="apparmor_parser"
[   93.078276] audit: type=1400 audit(1666029640.919:10): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/sbin/tcpdump" pid=1093 comm="apparmor_parser"
[   93.078838] audit: type=1400 audit(1666029640.919:11): apparmor="STATUS" operation="profile_load" profile="unconfined" name="virt-aa-helper" pid=1094 comm="apparmor_parser"
[   94.691346] ISO 9660 Extensions: Microsoft Joliet Level 3
[   94.691507] ISO 9660 Extensions: RRIP_1991A
[   95.424635] pps pps2: new PPS source ptp2
[   95.424671] ixgbe 0000:03:00.0: registered PHC device on eno1
[  105.461265] ixgbe 0000:03:00.0 eno1: NIC Link is Up 10 Gbps, Flow Control: None
[  105.461463] IPv6: ADDRCONF(NETDEV_CHANGE): eno1: link becomes ready
[  105.729148] ixgbe 0000:03:00.0 eno1: NIC Link is Down
[  106.532469] ixgbe 0000:03:00.0 eno1: NIC Link is Up 10 Gbps, Flow Control: None
[  119.547750] loop3: detected capacity change from 0 to 8
[  119.571930] Dev loop3: unable to read RDB block 8
[  119.640201]  loop3: unable to read partition table
[  119.640281] loop3: partition table beyond EOD, truncated
[  120.316603] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[  120.317195] virbr0: port 1(virbr0-nic) entered blocking state
[  120.317197] virbr0: port 1(virbr0-nic) entered disabled state
[  120.317252] device virbr0-nic entered promiscuous mode
[  120.322118] bpfilter: Loaded bpfilter_umh pid 1445
[  120.322262] Started bpfilter
[  120.421138] virbr0: port 1(virbr0-nic) entered blocking state
[  120.421142] virbr0: port 1(virbr0-nic) entered listening state
[  120.435656] virbr0: port 1(virbr0-nic) entered disabled state
[  120.466324] kauditd_printk_skb: 21 callbacks suppressed
[  120.466327] audit: type=1400 audit(1666029667.813:33): apparmor="DENIED" operation="capable" profile="libvirtd" pid=1416 comm="libvirtd" capability=17  capname="sys_rawio"
[ 1411.445667] kvm: vcpu 1: requested 38702 ns lapic timer period limited to 200000 ns
[ 1411.447305] kvm: vcpu 3: requested 38702 ns lapic timer period limited to 200000 ns
[ 1411.447314] kvm: vcpu 2: requested 38702 ns lapic timer period limited to 200000 ns
```

**Comment by Daviiap** [comment]
Running `uname -r` inside the VM with SNP disabled, i got `5.4.0-128-generic`

**Comment by tlendacky** [comment]
It sounds like the wrong kernel is booting. You should see 5.19.0-rc6-snp-guest-d9bd54fea4d2.

Did you change the grub menu to not be hidden and give you an opportunity to select the entry you want to boot?

**Comment by Daviiap** [comment]
No, I got no opportunity to select the entry...

**Comment by tlendacky** [comment]
> Disable the hidden grub menu boot and set a boot timeout value other than 0 (update /etc/default/grub), e.g:
> 
> * #GRUB_TIMEOUT_STYLE=hidden
> * GRUB_TIMEOUT=10
> 
> While at it, be sure that "console=tty0 console=ttyS0,115200n8 earlyprintk=serial" are part of the default command line arguments, e.g.:
> 
> * GRUB_CMDLINE_LINUX_DEFAULT="console=tty0 console=ttyS1,115200n8 earlyprintk=serial"
> 
> I also typically add this in order to get grub on the serial console:
> 
> * GRUB_TERMINAL_INPUT="serial gfxterm"
> * GRUB_TERMINAL_OUTPUT="serial gfxterm"
> * GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=1 --word=8 --parity=no --stop=1"
> 
> And don't forget to run update-grub.

Please be sure to do all of these so that you have an opportunity to select the kernel entry.

**Comment by Daviiap** [comment]
Found the error, had to change theese configs in /etc/default/grub.d/50-cloudimg-settings.cfg file.
But, no other kernel option in grub menu :/

**Comment by tlendacky** [comment]
Did  you install the guest kernel? If there's no grub entry, it certainly seems like you haven't installed it in the guest.

**Comment by Daviiap** [comment]
I've made the build of the Guest kernel, and passed the options -kernel and -initrd passing the builds.
The guest was able to launch, but it initialized in a Busybox mode:

![image](https://user-images.githubusercontent.com/48532328/196440542-0b4d9033-a7ad-4bc7-b7b3-076dd2e6de8c.png)

**Comment by tlendacky** [comment]
> I've made the build of the Guest kernel, and passed the options -kernel and -initrd passing the builds.
> The guest was able to launch, but it initialized in a Busybox mode:

That's because you probably didn't supply the -append argument that identifies the rootfs.

Please just boot the guest in non-SEV mode, transfer the guest .deb files to the guest and install them.

**Comment by Daviiap** [comment]
IT WORKED!!! Thanks a lot @tlendacky!!!
Just one more question, how does the SNP enabled Guest communicates with the SEV-SNP firmware? There is anything like /dev/sev insite the Guest VM that allows the Guest to send commands directly to the firmware?

**Comment by tlendacky** [comment]
If you do "modprobe sev-guest", that will load a driver that has an ioctl interface to retrieve the (extended) attestation report or get a derived key. Those are the only guest message services currently available.
