### ISSUE TITLE
generating the id block for SNP_LAUNCH_FINISH

### ISSUE THREAD

**Issue by aep** [AMDESE/AMDSEV#120]
do we have a tool to generate the id-block for snp?
i cant figure out the format from the SNP documenation. it just says "must be a valid sPA" but doesnt explain what that is (chapter 10 might be missing it from the public doc?)

**Comment by tlendacky** [comment]
The format of the id-block is documented in the SNP API document. It is supplied as a parameter, in base64 format, on the qemu command line sev-snp-guest object parameter. If you're using the launch script, then you'll need to update it to provide an id-block parameter.
