### ISSUE TITLE
Build broken as of today (sev-snp-devel)

### ISSUE THREAD

**Issue by rhomber** [AMDESE/AMDSEV#126]
make: Leaving directory '/tmp/test/AMDSEV/linux/guest'
+ run_cmd make -C guest -j 128 LOCALVERSION=
+ echo 'make -C guest -j 128 LOCALVERSION='
+ eval 'make -C guest -j 128 LOCALVERSION='
++ make -C guest -j 128 LOCALVERSION=
arch/x86/kvm/svm/sev.c: In function ‘sev_flush_asids’:
arch/x86/kvm/svm/sev.c:112:6: error: ‘sev_snp_enabled’ undeclared (first use in this function); did you mean ‘sev_es_enabled’?
  112 |  if (sev_snp_enabled)
      |      ^~~~~~~~~~~~~~~
      |      sev_es_enabled
arch/x86/kvm/svm/sev.c:112:6: note: each undeclared identifier is reported only once for each function it appears in
arch/x86/kvm/svm/sev.c: In function ‘sev_mem_enc_ioctl’:
arch/x86/kvm/svm/sev.c:2298:8: error: ‘sev_snp_enabled’ undeclared (first use in this function); did you mean ‘sev_es_enabled’?
 2298 |   if (!sev_snp_enabled) {
      |        ^~~~~~~~~~~~~~~
      |        sev_es_enabled
make[2]: *** [scripts/Makefile.build:249: arch/x86/kvm/svm/sev.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [scripts/Makefile.build:466: arch/x86/kvm] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1843: arch/x86] Error 2
make: *** Waiting for unfinished jobs....
+ echo 'ERROR: make -C guest -j 128 LOCALVERSION='
+ exit 1

It worked yesterday, so something has changed I guess?

**Comment by rhomber** [comment]
I didn't mention that because I literally just followed the instructions:

# git clone https://github.com/AMDESE/AMDSEV.git
# git checkout sev-snp-devel
# ./build.sh --package
# sudo cp kvm.conf /etc/modprobe.d/

Though, I would suggest you fix this readme to add a "cd AMDSEV"  after the clone as well :)

This was all working last night.

**Comment by Daviiap** [comment]
It looks is an error with qemu build...
You can build qemu manually, cloning the repo: https://github.com/AMDESE/qemu/tree/snp-v3 in branch `snp-v3`

```sh
DEST="<<Where you want to build qemu (absolute path)>>"
./configure --target-list=x86_64-softmmu --prefix=$DEST
make -j $(getconf _NPROCESSORS_ONLN) LOCALVERSION=
make -j $(getconf _NPROCESSORS_ONLN) LOCALVERSION= install
```

Try to build it manually and see if it works

**Comment by rhomber** [comment]
This seems to be working again now. Not sure what the issue was really.

Sorry!
