### ISSUE TITLE
SEND_UPDATE_VMSA returns error 4 (INVALID_LENGTH)

### ISSUE THREAD

**Issue by mincheolsung** [AMDESE/AMDSEV#130]
Hi,

I am trying to call SEND_UPDATE_VMSA with hdr_len = 52, guest_len = 4096 and trans_len = 4096 but the command returned an error 4 (INVALID_LENGTH).
As far as I know, the VMSA is always 4096 bytes. Why did the command fail?

Mincheol

**Comment by mincheolsung** [comment]
Has anyone had the same issue before?
I really don't know how to debug this error.

**Comment by RARelph** [comment]
Please provide dumps of the SEND_UPDATE_VMSA command buffer (Table 70 in the spec) and the SEND_UPDATE_VMSA packet header buffer (Table 71). Both before and after command execution.

**Comment by mincheolsung** [comment]
@RARelph 

1. Command buffer:
handle: 1
reserved1: 0
hdr_address: 0x8000105c56ac0
hdr_len: 52
reserved2: 0
guest_address: 0x800011b07a000
guest_len: 4096
reserved3: 0
trans_addr: 0x8000100d82000
trans_len: 4096
**sev command 0x42 failed (0x00000004)**
handle: 1
reserved1: 0
hdr_address: 0x8000105c56ac0
hdr_len: 52
reserved2: 0
guest_address: 0x800011b07a000
guest_len: 4096
reserved3: 0
trans_addr: 0x8000100d82000
trans_len: 4096

2. Hdr buffer:
compressed: 0x0
iv_low 0x0
iv_high: 0x0
mac0: 0x0
mac1: 0x0
mac2: 0x0
mac3: 0x0
**sev command 0x42 failed (0x00000004)**
compressed: 0x0
iv_low 0x0
iv_high: 0x0
mac0: 0x0
mac1: 0x0
mac2: 0x0
mac3: 0x0

**Comment by RARelph** [comment]
What happens if you do SEND_UPDATE_DATA with the same parameters instead of SEND_UPDATE_VMSA?

**Comment by mincheolsung** [comment]
SEND_UPDATE_DATA worked well.

**Comment by RARelph** [comment]
OK, so forgive the dumb questions here...
I presume you did an SEV INIT or SEV INIT_EX with ES enabled and that succeeded.
And you did a LAUNCH_START sequence for an SEV-ES guest through LAUNCH_FINISH successfully.
And you did a SEND_START that succeeded as well.

What version of SEV FW are you running?

**Comment by mincheolsung** [comment]
Yes, all the steps you mentioned worked well.
It is 1.53

**Comment by RARelph** [comment]
1.53... what's the next digit?

**Comment by RARelph** [comment]
I've assumed this is Milan... but just realized I haven't asked. What Epyc part are you running on?

**Comment by mincheolsung** [comment]
I assume you asked the CPU model?
It is EPYC 7313P 16-Core Processor.

**Comment by RARelph** [comment]
Question: I know the GUEST_PADDR is required to have the C-bit set. The VMSA is encrypted with the guest memory encryption key, so we want that. But why are you setting the C-bit on TRANS_PADDR and HDR_PADDR? Are you running your kernel with mem_encrypt=on? That would be unusual, but not invalid.

That's really just a shot in the dark. Having those set shouldn't cause a problem - assuming mem_encrypt=on - and regardless, it shouldn't produce an INVALID_LENGTH error. I know AMD tests all of the SEV APIs with mem_encrypt=on and without it.

What is the address of the command buffer?

**Comment by mincheolsung** [comment]
Yes, I am running the host OS with mem_encrypt=on.

The command buffer's VA is 0x90ad2cdf and the PA is 0xb770602fb68.

**Comment by RARelph** [comment]
Do you know what value is being placed in the SEV CmdBufAddr_Hi and _Lo registers?

**Comment by mincheolsung** [comment]
Can I find them by reading phys_lsb, phys_msb?

I found the code snippet below:
iowrite32(phys_lsb, sev->io_regs + sev->vdata->cmdbuff_addr_lo_reg);
iowrite32(phys_msb, sev->io_regs + sev->vdata->cmdbuff_addr_hi_reg);

Looks like the values in the SEV CmdBufAddr_Hi and _Lo registers are written on phys_lsb, phys_msb.

**Comment by RARelph** [comment]
Maybe. That looks like it makes sense. I'm not an expert on that side of the interface. Is that followed by an iowrite32() to the SEV CmdResp register, and then wait for the command to complete somehow?

**Comment by RARelph** [comment]
And, just as an experiment, I'd recommend rebooting the system without mem_encrypt=on to see if that changes anything.

**Comment by mincheolsung** [comment]
Now it worked without mem_encrypt=on.
Thanks!!

**Comment by RARelph** [comment]
I'm glad it's working for you. You should find the system a tiny bit (1-2%) faster now, too. But it SHOULD work with mem_encrypt=on as well as without it. I'll look in to that a bit further. But happy to see this closed.
