### ISSUE TITLE
SEV-SNP support in libvirtd

### ISSUE THREAD

**Issue by nicopal** [AMDESE/AMDSEV#134]
hi, trying to investigate if there has been any progress on adding SEV-SNP support in libvirt. Looks like by now there is support in Qemu for launching sev-snp machines. Do you know if there is ongoing work/plans on adding support for sev-snp in libvirtd?

              > @tlendacky got it, thanks! Is there any plan to support SNP in libvirtd? Where can I find topic about it?

             > Eventually, but first the Qemu support has to be ironed out. There was an RFC series submitted to Qemu, but that will also depend on the final KVM host series, which is still being worked on at the moment.

_Originally posted by @tlendacky in https://github.com/AMDESE/AMDSEV/issues/86#issuecomment-1074371949_

**Comment by tlendacky** [comment]
> hi, trying to investigate if there has been any progress on adding SEV-SNP support in libvirt. Looks like by now there is support in Qemu for launching sev-snp machines. Do you know if there is ongoing work/plans on adding support for sev-snp in libvirtd?

The Qemu support is not finalized, yet, so it is not upstream, which means no libvirt support, yet, either.

**Comment by nicopal** [comment]
Thanks, closing the issue.
