### ISSUE TITLE
Linux Kernel 5.19/Ubuntu22.10

### ISSUE THREAD

**Issue by khushboo-dfn** [AMDESE/AMDSEV#144]
https://www.phoronix.com/review/linux-519-features 
Linux kernel 5.19 is said to have support for SNP. If we use stock kernel in Ubuntu 22.10 as our host kernel what features would we be missing?
Basically, would like to understand what is the difference between Linux kernel 5.19 and Linux host kernel built with AMDESE fork? Need to plan our releases. Much appreciated!

**Comment by tlendacky** [comment]
Host/Hypervisor support for SNP is not yet upstream. 5.19 includes support for running as an SNP guest.

**Comment by khushboo-dfn** [comment]
Thanks for the reply @tlendacky ..do you know if there is a timeline for when the Host support will be upstream?

**Comment by tlendacky** [comment]
Hard to say, it is dependent on the UPM (unmapped private memory) support which is not upstream, yet. Hopefully soon...
