### ISSUE TITLE
SEV-SNP: launch VM failed with invalid parameter

### ISSUE THREAD

**Issue by whalefffall** [AMDESE/AMDSEV#146]
When I use the command `./launch-qemu.sh -hda ../ubuntu2.qcow2 -sev-snp`  in the branch `snp-latest` to launch my VM, I get the error message from qemu
```
Launching VM ..
  /tmp/cmdline.415156
qemu-system-86 64: -object memory-backend-memfd-private, id-ram1,size-2048M,share-true: Parameter 'qom-type' does not accept value 'memorv-backend-memfd-private'
```
The host is the latest SNP host `6.1.0-rc4-snp-host-db73108c4fd6`.

The installed guest `ubuntu2.qcow2` is created with the command `./launch-qemu.sh -hda ../ubuntu2.qcow2 -cdrom ../ubuntu-20.04.5-live-server-amd64.iso`. The iso file is downloaded from the official site of Ubuntu. 

It seems that this is a compile error?

**Comment by mdroth** [comment]
> Launching VM ..
>   /tmp/cmdline.415156
> qemu-system-86 64: -object memory-backend-memfd-private, id-ram1,size-2048M,share-true: Parameter 'qom-type' does not accept value 'memorv-backend-memfd-private'

I'm not really sure what's going on with this command-line. The launch-qemu.sh script on snp-latest branch of AMDSEV scripts specifies "id=ram1", whereas your command-line somehow has "id-ram1".  That will surely break.

There's also a space there before the id-ram...I don't know if that was a formatting error from copy/paste here, but if not it would likely break QEMU's command-line parsing.

Also, your error message suggests a mispelled "memorv-backend-memfd-private" argument is being passed in, but in the snp-latest launch-qemu.sh script there is no such mispelling. There's also isn't a mispelling of that sort in snp-latest QEMU tree, and even in your error message the "-object memory-backend-memfd-private" is spelled correctly which makes the error message even more perplexing.

Please make sure you don't have any local changes or things of that sort.

**Comment by whalefffall** [comment]
Oops. Thanks for your reply. I made several spelling mistakes. Here is a screenshot of the command and the error message. I do not make any changes to the script.
![issue146](https://user-images.githubusercontent.com/106544758/232282589-337e5a2c-cecf-4bba-952c-c77dfcf62c03.png)

**Comment by tlendacky** [comment]
Have you built the version of Qemu specified in snp-latest branch of the AMDSEV repo? That is, the snp-latest branch of the qemu repo?

**Comment by whalefffall** [comment]
Thanks! @tlendacky. I built QEMU for version 7.0.0 however I realize that the version of Qemu specified in snp-latest branch of the AMDSEV repo is 7.2.0. Now it can work!
