### ISSUE TITLE
SNP: futher verification for whether snp is enable

### ISSUE THREAD

**Issue by whalefffall** [AMDESE/AMDSEV#147]
I followed the instructions in the branch `snp-latest` and launch my VM with SNP enabled successfully. 

Now I want to verify whether snp is **really enabled** in my VM, more than simply using the command `dmesg | grep -i snp`. Can you offer me some guidance or documents?

I tried to use qmp to observe the memory of VM from the host (use the command `pmemsave`  to dump memory and see the saved `raw` file ), and I got mostly 0s for the SNP disabled guest and the SNP guest, and got messy code (at the start, the rest is still mostly 0s) for the SEV guest and SEV-ES guest. It's confusing why I got mostly 0s for the SNP guest.

Moreover, after defining a qmp port, I append a parameter `-monitor unix:/tmp/qemu-sev.sock,server,nowait` to launch the VM and use the command `socat - UNIX-CONNECT:/tmp/qemu-sev.sock` on the host to connect the QEMU monitor. I found that the command `info mem` would return a lot of active virtual memory mappings for VM with no memory encryption, and return nothing for VM with memory encryption (SEV, SEV-ES and SNP). Could this be part of the verification?

**Comment by RARelph** [comment]
See the AMD64 Architecture Programmer's Manual, Volume 2, section 15.34.10. That describes the SEV_STATUS MSR, which cannot be intercepted by the hypervisor and provides information about what flavor of SEV (plain SEV, SEV-ES, or SEV-SNP) the guest is running under.

**Comment by whalefffall** [comment]
@RARelph Thanks for your reply!
