### ISSUE TITLE
Family ID and Image ID in the ID Block

### ISSUE THREAD

**Issue by sza-1** [AMDESE/AMDSEV#163]
The SEV-SNP specification rev. 1.54 says that Family and Image IDs provided by the guest owner and uninterpreted by the firmware.

It is not clear why these fields named FAMILY_ID and IMAGE_ID. Does it mean that guest owner may freely use these 256 bits of ID Block struct to pass any custom data for their own needs, and the meaning of these fields is not planned to change in the following SEV-SNP firmware revisions?

**Comment by tlendacky** [comment]
> Does it mean that guest owner may freely use these 256 bits of ID Block struct to pass any custom data for their own needs, and the meaning of these fields is not planned to change in the following SEV-SNP firmware revisions?

Yes

**Comment by sza-1** [comment]
> > Does it mean that guest owner may freely use these 256 bits of ID Block struct to pass any custom data for their own needs, and the meaning of these fields is not planned to change in the following SEV-SNP firmware revisions?
> 
> Yes

Thanks!
