### ISSUE TITLE
Changes to enable measured direct boot and run SEV-SNP guests correctly?

### ISSUE THREAD

**Issue by gianlucascopelliti** [AMDESE/AMDSEV#198]
Hi,

I would like to try out measured direct boot in order to include the measurements of kernel, initrd and kernel arguments to the attestation report of a SEV-SNP guest. So far I've been experimenting from the `snp-latest` branch but without success.

As far as I understand (e.g., from https://github.com/AMDESE/AMDSEV/issues/93#issuecomment-1514158728), to enable this we first need to build OVMF from `OvmfPkg/AmdSev/AmdSevX64.dsc`. This generates a single `OVMF.fd` file instead of two separate `OVMF_CODE.fd` and `OVMF_VARS.fd` files.

Now, what are the next steps to do? In particular, what would we need to change in `launch_qemu.sh` / qemu in order to set things up correctly? My question is not only related to the `OVMF.fd` file itself, but more in general to all the qemu arguments that would differ compared to the "normal" way (i.e., without measured direct boot).

Thanks!

**Comment by tlendacky** [comment]
You would need to update the launch_qemu.sh script to specify only a single "-drive if=pflash,..." argument specifying the OVMF.fd file. Then you would need to add the -kernel, -initrd and -append arguments to boot everything directly using the specified kernel, initrd and command line arguments. Additionally, you need to "kernel-hashes=on" to the sev-snp-guest object definition.

I don't run this very often, so I think that is all that is needed, but YMMV.

**Comment by gianlucascopelliti** [comment]
Indeed, this works, thanks! I had tried this previously but I could not boot the guest due to some error, but now I have rebuilt QEMU and OVMF and it's working.

Side note: when using `-kernel` and `-initrd` it could not boot the guest properly but went to recovery mode (initramfs). To solve this issue, I had to run the guest normally (without `-kernel`) and run `sudo update-initramfs -u`. After that, trying direct boot again worked correctly.

**Comment by gianlucascopelliti** [comment]
Sorry, actually I was mistaken, it's still not working properly. 

I found out that if I add `kernel-hashes=on` it always boots in recovery mode and I'm basically stuck. Instead, using `kernel-hashes=off` boots normally.

Any advice?

**Comment by tlendacky** [comment]
There should be some output from OVMF. Look for messages prefixed with BlobVerifierLibSevHashesConstructor and/or VerifyBlob.

**Comment by dubek** [comment]
When `kernel-hashes=off` I'd expect OVMF (if built as AmdSevX64) to not allow booting the kernel at all. A look into the OVMF logs per @tlendacky 's suggestion might be a good start.

Also try running qemu with tracing of `kvm_sev_*` logs to see if it reveals anything.

**Comment by gianlucascopelliti** [comment]
Thanks for your responses. I tried again (rebuilding the kernel, QEMU and OVMF just to be sure) and I confirm what I wrote last time. Note that I built again OVMF from `AmdSevX64.dsc`:

- With `kernel-hashes=off`, it just boots normally without verifying the kernel. However, I noticed that it *doesn't* boot the kernel passed as input, but the usual one installed in the VM image.
- With `kernel-hashes=on`, OVMF verifies the hashes correctly, and then correctly boots the kernel passed as input (I verified with `uname -r`). From here, however, it goes in recovery mode (indeed it seems like it can't find the root drive).

Below is the output from the hash verification done by OVMF:
```
BlobVerifierLibSevHashesConstructor: Found injected hashes table in secure location
Select Item: 0x17
Select Item: 0x8
FetchBlob: loading 11533440 bytes for "kernel"
Select Item: 0x18
Select Item: 0x11
VerifyBlob: Found GUID 4DE79437-ABD2-427F-B835-D5B172D2045B in table
VerifyBlob: Hash comparison succeeded for "kernel"
Select Item: 0xB
FetchBlob: loading 111096191 bytes for "initrd"
Select Item: 0x12
VerifyBlob: Found GUID 44BAF731-3A2F-4BD7-9AF1-41E29169781D in table
VerifyBlob: Hash comparison succeeded for "initrd"
Select Item: 0x14
FetchBlob: loading 48 bytes for "cmdline"
Select Item: 0x15
VerifyBlob: Found GUID 97D02DD8-BD20-4C94-AA78-E7714D36AB2A in table
VerifyBlob: Hash comparison succeeded for "cmdline"
```

Tracing `kvm_sev_*` did not reveal anything interesting, just the logs below:
```
kvm_sev_init type SEV-SNP flags 0x0
qemu-system-x86_64: warning: Restricted memory (UPM) enabled, disabling SMM. Memory discard mode: none
kvm_sev_snp_launch_start policy 0x30000 gosvw (null)
kvm_sev_change_state uninit -> launch-update
qemu-system-x86_64: warning: kvm_create_gmemfd: created memfd: 17, size: 80000000, flags: 1
qemu-system-x86_64: warning: creating ROM device with private memory.
qemu-system-x86_64: warning: kvm_create_gmemfd: created memfd: 23, size: 400000, flags: 1
qemu-system-x86_64: warning: kvm_create_gmemfd: created memfd: 25, size: 20000, flags: 0
qemu-system-x86_64: warning: kvm_create_gmemfd: created memfd: 27, size: 20000, flags: 0
kvm_sev_snp_launch_update addr 0x7f4e4b000000 gpa 0xffc00000 len 0x400000 (Normal page)
kvm_sev_snp_launch_update addr 0x7f4e4c600000 gpa 0x800000 len 0x9000 (Zero page)
kvm_sev_snp_launch_update addr 0x7f4e4c60a000 gpa 0x80a000 len 0x3000 (Zero page)
kvm_sev_snp_launch_update addr 0x7f4e4c60d000 gpa 0x80d000 len 0x1000 (Secrets page)
kvm_sev_snp_launch_update addr 0x7f4e4c60e000 gpa 0x80e000 len 0x1000 (Cpuid page)
kvm_sev_snp_launch_update addr 0x7f4e4c60f000 gpa 0x80f000 len 0x1000 (Normal page)
kvm_sev_snp_launch_update addr 0x7f4e4c610000 gpa 0x810000 len 0x10000 (Zero page)
kvm_sev_snp_launch_finish id_block (null) id_auth (null) host_data (null)
kvm_sev_change_state launch-update -> running
```

I'll try to figure out why it doesn't boot properly. Will keep you updated.

**Comment by gianlucascopelliti** [comment]
I was finally able to boot properly using a fresh disk image (created with `debootstrap`) and passing `root=/dev/sda` to the kernel arguments.

I still haven't figured out why my previous image isn't booting properly, but it seems obvious now that it's not a problem related to SEV-SNP. Hence, I'll close this issue.

**Comment by enuoCM** [comment]
> I was finally able to boot properly using a fresh disk image (created with `debootstrap`) and passing `root=/dev/sda` to the kernel arguments.

@gianlucascopelliti I'm facing the same problem. With kernel-hashes=on, the booted vm doesn't has /dev/sev-guest device, but `dmesg | grep -i -e rmp -e sev` output seems fine:
```
[    0.550548] Memory Encryption Features active: AMD SEV SEV-ES SEV-SNP
[    0.682529] SEV: APIC: wakeup_secondary_cpu() replaced with wakeup_cpu_via_vmgexit()
[    0.757173] SEV: Using SNP CPUID table, 31 entries present.
[    1.197467] SEV: SNP guest platform device initialized.
```
Do you have this issue?

**Comment by gianlucascopelliti** [comment]
Hi @enuoCM,

Uhm no, I did not have this issue. From the `dmesg` output I have an additional line that you don't have:

```
[    4.917243] sev-guest sev-guest: Initialized SEV guest driver (using vmpck_id 0)
```

I assume you are using the latest SNP-enabled kernel built from the `snp-latest` branch?
