### ISSUE TITLE
Pagefault in AmdSevDxe.dll

### ISSUE THREAD

**Issue by jetguy1256** [AMDESE/AMDSEV#2]
I have done everything like in the README and it seems like booting **without** "-nosev" option gives me the following errors (attached in logfile),
booting with "./launch-qemu.sh -hda ubuntu.qcow2 -nosev -vnc 1" boots ok

[stdout.log](https://github.com/AMDESE/AMDSEV/files/1590073/stdout.log)

**Comment by sbrijesh** [comment]
The following commit looks a bit interesting. Can you please try booting the SEV guest just before this commit and let me know if it works. 

 commit 2ac1730bf2a51d6d0483347a0218e1768d6d7992
 Author: Jian J Wang <jian.j.wang@intel.com>
 Date:   Tue Nov 28 21:49:31 2017 +0800
 MdeModulePkg/DxeIpl: Mark page table as read-only

**Comment by jetguy1256** [comment]
Awesome!, modified the install script and now it works

**Comment by sbrijesh** [comment]
OK, I will take a look at it and will send the fix upstream.
