### ISSUE TITLE
SEV-SNP: RMPUPDATE failed (SEV: too many firmware commands are in progress)

### ISSUE THREAD

**Issue by csegarragonz** [AMDESE/AMDSEV#205]
Hi!

Our SEV-SNP enabled host started doing unexpected warm resets a couple of days ago.
At the beginning, the host would successfully boot after reset, but now it hangs after a RMPUPDATE failure.
(Note that both the reset, and of course the reset and hang, are unexpected)

The RMPUPDATE failure reads something like:

```bash
SEV-SNP: RMPUPDATE failed ...
```

and then it hangs in:

```bash
ccp .. SEV: too many firmware commands are in progress
```
any idea of what could be happening?

FWIW, the only thing I can see in the `journalctl` are the aforementioned:

```bash
Feb 21 17:59:09 milan2 kernel: ccp 0000:01:00.5: SEV: too many firmware commands are in-progress, no command buffers available.
```

I also include a screenshot of the virtual console from iDRAC of the host that fails to boot:

![image](https://github.com/AMDESE/AMDSEV/assets/19322012/5df30152-e5c0-4371-8bf0-060c4d454976)

**Comment by csegarragonz** [comment]
Hi,

This morning the machine is unreachable after a power cycle last night with a different error:

![image](https://github.com/AMDESE/AMDSEV/assets/19322012/1a7e165d-c789-4917-8bf2-c82f8cbd7aa8)

Any idea of what could be going on?

**Comment by mdroth** [comment]
This issue should be fixed in the latest linux/QEMU trees that were pushed yesterday, so please give those a try.

**Comment by csegarragonz** [comment]
It does, many thanks!
