### ISSUE TITLE
Launch qemu with USE_DEFAULT_NETWORK not working?

### ISSUE THREAD

**Issue by roostab** [AMDESE/AMDSEV#214]
Hi,

When activating USE_DEFAULT_NETWORK I get the following error:
```
qemu-system-x86_64: -netdev user,id=vmnic,hostfwd=tcp::8000-:22: network backend 'user' is not compiled into this binary
```

Is there an alternative to get a VM with connectivity? 

Thanks

**Comment by aik** [comment]
You need to install  libslirp-devel (Fedora) or  libslirp-dev (Ubuntu) and recompile QEMU with running its ./configure first.

**Comment by roostab** [comment]
Thanks!
