### ISSUE TITLE
SEV-SNP VM Accessing VMSA Area During Runtime

### ISSUE THREAD

**Issue by jaeyoon-kim-dev** [AMDESE/AMDSEV#219]
Hi, I have one question regarding whether it is possible for a SEV-SNP VM (running on default VMPL0) to access and read its own initial VMSA area during runtime.

I'm aware that higher privileged VMPLs can read and manipulate lower privileged VMPLs, but it is not clear whether a VMPL0 can access its own VMSA.

In the source code, the `#define INITIAL_VMSA_GPA 0xFFFFFFFFF000` initial VMSA is fixed in a constant GPA, which typically does not get mapped into the guest GPA range. I tried to manually assign the guest mapping, but the #NPF (0x500000004) and #NPF (0x580000005, RMP fault) do not get resolved, repeatedly resulting in sequence when I enabled the C-bit of the page in the guest. Accessing without setting the C-bit works fine but shows encrypted content as read on the host side.

**Question Reiteration:**
Is there a specific procedure or additional configuration required to allow a SEV-SNP VM to access and read its own VMSA area during runtime?

**Comment by tlendacky** [comment]
In the case of the VM running at VMPL0, the VMSA of the BSP is not mapped into guest memory by KVM, so the BSP won't be able to access its own VMSA. For the APs, it is similar until an AP is started using the AP Create call. At the point that Linux is in control, the VMSAs are allocated by the Linux kernel and accessible to the VM and used to start the APs.
