### ISSUE TITLE
snp not working with linux kernel 6.11-rc3

### ISSUE THREAD

**Issue by NemoTR** [AMDESE/AMDSEV#226]
CPU: 7313
snp worked well with linux kernel 6.9-rc1 but failed with kernel 6.11-rc3 when updated to the latest snp-latest kernel.

``` bash
# uname -r
6.11.0-rc3-snp-host-85ef1ac03941
# snphost ok
[ PASS ] - AMD CPU
[ PASS ]   - Microcode support
[ PASS ]   - Secure Memory Encryption (SME)
[ PASS ]     - SME: Enabled in MSR
[ PASS ]   - Secure Encrypted Virtualization (SEV)
[ PASS ]     - Encrypted State (SEV-ES)
[ PASS ]       - SEV-ES INIT: Enabled
[ PASS ]     - SEV INIT: SEV is INIT, but not currently running a guest
[ PASS ]     - Secure Nested Paging (SEV-SNP)
[ PASS ]       - VM Permission Levels
[ PASS ]         - Number of VMPLs: 4
[ FAIL ]       - SNP: Disabled in MSR
[ PASS ]       - SEV Firmware Version: Sev firmware version: 1.55
[ FAIL ]       - SNP INIT: Failed to get SNP Platform status unable to retrieve SNP platform status
[ PASS ]     - Physical address bit reduction: 5
[ PASS ]     - C-bit location: 51
[ PASS ]     - Number of encrypted guests supported simultaneously: 509
[ PASS ]     - Minimum ASID value for SEV-enabled, SEV-ES disabled guest: 233
[ PASS ]     - Reading /dev/sev: /dev/sev readable
[ PASS ]     - Writing /dev/sev: /dev/sev writable
[ PASS ]   - Page flush MSR: ENABLED
[ PASS ] - KVM supported: API version: 12
[ PASS ]   - SEV enabled in KVM: enabled
[ PASS ]   - SEV-ES enabled in KVM: enabled
[ FAIL ]   - SEV-SNP enabled in KVM: Error - contents read from /sys/module/kvm_amd/parameters/sev_snp: N
[ PASS ] - Memlock resource limit: Soft: 33683374080 | Hard: 33683374080
[ PASS ] - RMP table addresses: Addresses: 1416626176 - 1954545663
[ FAIL ] - RMP INIT: Failed to get SNP Platform status unable to retrieve SNP platform status
[ FAIL ] - Comparing TCB values: Failed to get SNP Platform status unable to retrieve SNP platform status
ERROR: One or more tests in sevctl-ok reported a failure
Error: One or more tests in sevctl-ok reported a failure
```

```bash 
# dmesg | grep -i sev
[    0.000000] SEV-SNP: RMP table physical range [0x0000000054700000 - 0x00000000747fffff]
[    0.916364] SEV-SNP: Memory reserved for the RMP table does not cover full system RAM (expected 0x406f5000 got 0x20100000)
[    2.707598] ccp 0000:43:00.1: sev enabled
[    2.765801] ccp 0000:43:00.1: SEV firmware update successful
[    2.803758] ccp 0000:43:00.1: SEV API:1.55 build:21
[    2.803765] ccp 0000:43:00.1: SEV API:1.55 build:21
[    2.885554] kvm_amd: SEV enabled (ASIDs 233 - 509)
[    2.885556] kvm_amd: SEV-ES enabled (ASIDs 1 - 232)
[    2.885558] kvm_amd: SEV-SNP disabled (ASIDs 1 - 232)
```

```bash 
# rdmsr -a 0xC0010010
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
2f40000
# wrmsr -a 0xC0010010 0x3f40000
# rdmsr -a 0xC0010010
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
3f40000
# snphost ok
[ PASS ] - AMD CPU
[ PASS ]   - Microcode support
[ PASS ]   - Secure Memory Encryption (SME)
[ PASS ]     - SME: Enabled in MSR
[ PASS ]   - Secure Encrypted Virtualization (SEV)
[ PASS ]     - Encrypted State (SEV-ES)
[ PASS ]       - SEV-ES INIT: Enabled
[ PASS ]     - SEV INIT: SEV is INIT, but not currently running a guest
[ PASS ]     - Secure Nested Paging (SEV-SNP)
[ PASS ]       - VM Permission Levels
[ PASS ]         - Number of VMPLs: 4
[ PASS ]       - SNP: Enabled in MSR
[ PASS ]       - SEV Firmware Version: Sev firmware version: 1.55
[ FAIL ]       - SNP INIT: Failed to get SNP Platform status unable to retrieve SNP platform status
[ PASS ]     - Physical address bit reduction: 5
[ PASS ]     - C-bit location: 51
[ PASS ]     - Number of encrypted guests supported simultaneously: 509
[ PASS ]     - Minimum ASID value for SEV-enabled, SEV-ES disabled guest: 233
[ PASS ]     - Reading /dev/sev: /dev/sev readable
[ PASS ]     - Writing /dev/sev: /dev/sev writable
[ PASS ]   - Page flush MSR: ENABLED
[ PASS ] - KVM supported: API version: 12
[ PASS ]   - SEV enabled in KVM: enabled
[ PASS ]   - SEV-ES enabled in KVM: enabled
[ FAIL ]   - SEV-SNP enabled in KVM: Error - contents read from /sys/module/kvm_amd/parameters/sev_snp: N
[ PASS ] - Memlock resource limit: Soft: 33683374080 | Hard: 33683374080
[ PASS ] - RMP table addresses: Addresses: 1416626176 - 1954545663
[ FAIL ] - RMP INIT: Failed to get SNP Platform status unable to retrieve SNP platform status
[ FAIL ] - Comparing TCB values: Failed to get SNP Platform status unable to retrieve SNP platform status
ERROR: One or more tests in sevctl-ok reported a failure
Error: One or more tests in sevctl-ok reported a failure

**Comment by mdroth** [comment]
Do you have more details on what sort of machine/CPU you are running on? And if your BIOS has "CPU options->Split RMP table", can you state what it's currently set to, and try seeing if setting it to "disable" makes a difference? Also what do you have "RMP table coverage" set to in BIOS?

Full dmesg output would also be useful.

**Comment by tlendacky** [comment]
> ```shell
> [    0.000000] SEV-SNP: RMP table physical range [0x0000000054700000 - 0x00000000747fffff]
> [    0.916364] SEV-SNP: Memory reserved for the RMP table does not cover full system RAM (expected 0x406f5000 got 0x20100000)
> ```

It looks like the RMP table is not large enough. Check and ensure your RMP table BIOS options aren't limiting the size of the RMP table.

**Comment by NemoTR** [comment]
> Do you have more details on what sort of machine/CPU you are running on? And if your BIOS has "CPU options->Split RMP table", can you state what it's currently set to, and try seeing if setting it to "disable" makes a difference? Full dmesg output would also be useful.

Thanks for replying!
I  am using a server self-modified with:
CPU: EPYC 7313 x1
Mother Board: Gigabyte mz32-ar0 rev 3.x
Memory: 256GB
System: ubuntu 24.04lts
GPU: RTX 4090

There is not a "CPU options->Split RMP table" option in my BIOS, I found the "SNP Memory (RMP Table) Coverage" as shown below:
![image](https://github.com/user-attachments/assets/e7fea60d-6371-437f-bd1f-26a6e87ef05d)
I set this to "Custom" and gave it 200GB memory. This worked well with 6.9-rc1 (at least snp was able to init). Maybe I should try to set it to "Enable" (means fully covered) to try to make a difference tomorrow.

The current full dmesg is as follows:

[dmesg.txt](https://github.com/user-attachments/files/16677232/dmesg.txt)

**Comment by tlendacky** [comment]
> I set this to "Custom" and gave it 200GB memory.

This is the issue.

There is a bug in the 6.9-rc1 snp_probe_rmptable_info() function. At the point this function is invoked, max_pfn has not been set, so the check to ensure that the RMP table covers all of system RAM always passes. You are likely to run into problems later at some point if any of the memory that is outside the coverage of the RMP is attempted to be used for an SNP guest. That bug has been fixed and that is why you are now seeing the error message and SNP not being enabled.

Please set the option to "Enable" so that BIOS allocates an RMP table to cover all of system RAM.

**Comment by NemoTR** [comment]
> > I set this to "Custom" and gave it 200GB memory.
> 
> This is the issue.
> 
> There is a bug in the 6.9-rc1 snp_probe_rmptable_info() function. At the point this function is invoked, max_pfn has not been set, so the check to ensure that the RMP table covers all of system RAM always passes. You are likely to run into problems later at some point if any of the memory that is outside the coverage of the RMP is attempted to be used for an SNP guest. That bug has been fixed and that is why you are now seeing the error message and SNP not being enabled.
> 
> Please set the option to "Enable" so that BIOS allocates an RMP table to cover all of system RAM.

OK, thank you! I will have a try and come back to report.

**Comment by NemoTR** [comment]
> > I set this to "Custom" and gave it 200GB memory.
> 
> This is the issue.
> 
> There is a bug in the 6.9-rc1 snp_probe_rmptable_info() function. At the point this function is invoked, max_pfn has not been set, so the check to ensure that the RMP table covers all of system RAM always passes. You are likely to run into problems later at some point if any of the memory that is outside the coverage of the RMP is attempted to be used for an SNP guest. That bug has been fixed and that is why you are now seeing the error message and SNP not being enabled.
> 
> Please set the option to "Enable" so that BIOS allocates an RMP table to cover all of system RAM.

Yes, this worked. The problem was solved as soon as I set 'snp memory coverage' to 'Enable'. Thanks！
