### ISSUE TITLE
Hardware and software support on SEV-ES

### ISSUE THREAD

**Issue by sjtugjy** [AMDESE/AMDSEV#23]
I guess not all the AMD EPYC CPU support SEV-ES which is newer than SEV.
Is there any information on which specific CPU supports SEV-ES?

Besides, does SEV-ES requires specific motherboard/bios?

Last, any software supports SEV-ES now?

**Comment by RARelph** [comment]
All AMD EPYC CPUs have hardware support for SEV-ES as well as SEV (aka, SEV-MEM).
SEV (including SEV-ES) requires minimal BIOS support, but it DOES require BIOS support.
Additionally, the SEV-supporting ASIDs are divided up in to "requires SEV-ES" and "cannot use SEV-ES". This choice must be made by BIOS. By default, most BIOSes set this option to have all SEV-supporting ASIDs be "cannot use SEV-ES". There should be a BIOS setting that allows you to set the divider to a value somewhere between 1 (the common default, all ASIDs cannot use SEV-ES) and 16 (which would represent all ASIDs require SEV-ES). Where this BIOS option is, or even if this option is exposed, is up to the system vendor.

I am not sure what software supports SEV-ES today, if any.

**Comment by sjtugjy** [comment]
Thanks a lot!
