### ISSUE TITLE
On VMRK and VM-dependent key derivations

### ISSUE THREAD

**Issue by aadomn** [AMDESE/AMDSEV#241]
I'm trying to leverage [the key derivation functionality](https://www.amd.com/content/dam/amd/en/documents/epyc-technical-docs/specifications/56860.pdf#%5B%7B%22num%22%3A138%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C62%2C553%2C0%5D) within an SEV-SNP guest in order to derive VM-unique keys.
I am using the `VMRK` as root key since `VCEK`/`VLEK` are specifics to the platform/provider, and I don't want other guests with the exact same kernel etc to derive the same key.
I noticed that after restarting an SNP guest, the same `MSG_KEY_REQ` message with the exact same parameters led to a different derived key before and after restart: is it the expected behavior? I would have expected the derived key to remain unchanged as the `VMRK` is randomly generated during the launch process (and not modified afterwards).

More generally, are there some publicly available guidelines to leverage key derivations within an SEV-SNP guest?

Thanks for your support!

**Comment by Freax13** [comment]
SNP doesn't have the concept of "restarting" a VM. What's really happening is that the VM is destroyed and a new VM is created. This new VM will get a new VMRK which is why the derived keys differ.

**Comment by aadomn** [comment]
Makes sense, thank you!
