### ISSUE TITLE
Problem with AMD SEV-SNP and Linux kernel 6.11 and QEMU 9.1.0 - OVMF AmdSev

### ISSUE THREAD

**Issue by danko-miladinovic** [AMDESE/AMDSEV#242]
Hi everyone,

Sorry to bother you here, but does anybody know the solution to the problem of booting an SEV-SNP VM with Linux kernel 6.11 on the host and QEMU 9.1.5. The kernel is downloaded and installed from [here](https://kernel.ubuntu.com/mainline/v6.11/). I tried to run it with OVMF (more precisely `OvmfPkg/AmdSev/AmdSevX64.dsc`) and to run it with only kernel `6.6` and initramfs. The OVMF that is used is a single-image binary `OVMF.fd` that is built from `AmdSevX64.dsc`.

QEMU command:
```
$QEMU_BIN -enable-kvm \
   -smp 4 \
   -m 8G,slots=5,maxmem=10G \
   -cpu EPYC \
   -machine q35,confidential-guest-support=sev0,memory-backend=ram1 \
   -no-reboot \
   -netdev user,id=vmnic \
   -device virtio-net-pci,disable-legacy=on,iommu_platform=true,netdev=vmnic \
   -bios $OVMF_CODE \
   -object memory-backend-memfd,id=ram1,size=8G,share=true,prealloc=false \
   -object sev-snp-guest,id=sev0,cbitpos=51,reduced-phys-bits=1,kernel-hashes=on \
   -kernel $KERNEL -append "earlyprintk=serial console=ttyS0" \
   -initrd $INITRD \
   -nographic \
   -monitor pty \
   -monitor unix:monitor,server,nowait
```

I get this error:
```qemu-system-x86_64: kvm_set_user_memory_region: KVM_SET_USER_MEMORY_REGION2 failed, slot=2, start=0xffc84000, size=0x37c000, flags=0x2, guest_memfd=-1, guest_memfd_offset=0x0: Invalid argument```

Thanks.

Kind regards,
Danko

**Comment by tlendacky** [comment]
What is the value of $OVMF_CODE? Be sure you are using the OVMF.fd file and not the OVMF_CODE.fd file.

**Comment by danko-miladinovic** [comment]
Hi, thank you for the fast replay. It is a path to: `edk2/Build/AmdSev/DEBUG_GCC5/FV/OVMF.fd`

**Comment by danko-miladinovic** [comment]
Before building I created an empty `grub.efi` here `OvmfPkg/AmdSev/Grub/grub.efi`.

**Comment by tlendacky** [comment]
> qemu-system-x86_64: kvm_set_user_memory_region: KVM_SET_USER_MEMORY_REGION2 failed, slot=2, start=0xffc84000, size=0x37c000, flags=0x2, guest_memfd=-1, guest_memfd_offset=0x0: Invalid argument

What is the command line after all of the bash substitutions?

The size value of 0x37c000 is less than the 4MB BIOS code size that I would expect (0x37c000 is actually the size I always see for the OVMF_CODE.fd file when working with SEV and SEV-ES guests). Check that you are building the package properly or double-check that the environment variable is truly pointing where you think it is.

**Comment by danko-miladinovic** [comment]
Thank you. I will check and report back.

**Comment by danko-miladinovic** [comment]
Yes, sorry for bothering you. The problem was with OVMF path. It was pointing to an old OVMF. Thank you.
