### ISSUE TITLE
Building SEV-ES fails: ovmf submodule no longer exists

### ISSUE THREAD

**Issue by SudNeela** [AMDESE/AMDSEV#244]
I'm attempting to build SEV-ES ovmf using the `./build.sh` script, but it looks like one of the OVMF submodules (https://github.com/Zeex/subhook.git) no longer exists.

See issue:
https://github.com/tianocore/edk2/issues/6398 where it was reported 16-ish hours ago.

Reporting this here in case someone else runs into the issue.

**Comment by CookieComputing** [comment]
Yeah, also running into this issue (although not specifically from this repo, but rather for the SVSM project, see [this INSTALL guide](https://github.com/coconut-svsm/svsm/blob/main/Documentation/docs/installation/INSTALL.md#building-the-guest-firmware).

If you haven't found a workaround, can you try removing that dependency on `.gitmodules` in the imported `edk2` repo? I manually removed it from my SVSM version of `edk2` and got this to build, as it seems like the submodule in question is used for [some testing](https://github.com/tianocore/edk2/issues/6398#issuecomment-2453590333), which hopefully doesn't affect your actual build of `ovmf` binaries. You might have to do some hacking with that build script to get it to work.

**Comment by CookieComputing** [comment]
Just following up for closure: Seems like they merged this as of a few hours: https://github.com/tianocore/edk2/pull/6402#issue-2633506169, so I guess this transient dependency should be resolved by the next time you run the script.

**Comment by SudNeela** [comment]
Thanks for letting me know! We just resorted to using an older ovmf binary... which didn't work as well as we hoped (we have some custom things going on). I'll probably get back to compiling from source now :D

**Comment by ENOFLG** [comment]
Just for anyone currently stuck here: I'm working with SEV-SNP and got the build to work again by simply editing the AMDSEV/ovmf/.gitmodules, akin to the changes made here https://github.com/tianocore/edk2/pull/6402/files#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584
