### ISSUE TITLE
Error on Ubuntu 18.04

### ISSUE THREAD

**Issue by miloserdoff** [AMDESE/AMDSEV#249]
Hello. When entering the command ./build.sh --package I encountered a problem in that the repository with subhook 'https://github.com/Zeex/subhook.git/' was not found. I am attaching the error log to the message

Cloning into '/home/vadm/AMDSEV/ovmf/UnitTestFrameworkPkg/Library/SubhookLib/subhook'...
Username for 'https://github.com': ****** (My username)
Password for 'https://******@github.com': ****** (My password)
remote: Repository not found.
fatal: repository 'https://github.com/Zeex/subhook.git/' not found fatal: clone of 'https://github.com/Zeex/subhook.git' into submodule path '/home/vadm/AMDSEV/ovmf/UnitTestFrameworkPkg/Library/SubhookLib/subhook' failed Failed to clone 'UnitTestFrameworkPkg/Library/SubhookL ib/subhook'. Retry scheduled Cloning into '/home/vadm/AMDSEV/ovmf/UnitTestFrameworkPkg/Library/SubhookLib/subhook'... Username for 'https://github.com': ****** (My username) Password for 'https://******@github.com': ****** (My password) remote: Repository not found.
fatal: repository 'https://github.com/Zeex/subhook.git/' not found fatal: clone of 'https://github.com/Zeex/subhook.git' into submodule path '/home/vadm/AMDSEV/ovmf/UnitTestFrameworkPkg/Library/SubhookLib/subhook' failed Failed to clone 'UnitTestFrameworkPkg/Library/SubhookL ib/subhook' a second time, aborting ERROR: git submodule update --init --recursive

**Comment by buildmine10** [comment]
I cannot give you an answer to your problem. But I can redirect your search. This is probably an issue with git or GitHub. This is probably not a problem with this specific repository. At least all the errors look like things that git throws, when something goes wrong with git.

**Comment by miloserdoff** [comment]
@buildmine10 https://github.com/Zeex/subhook/ gives a 404 error

**Comment by miloserdoff** [comment]
@buildmine10 https://github.com/Zeex/subhook/ is close. I can't clone this repository.

**Comment by miloserdoff** [comment]
You need find https://github.com/Zeex/subhook in your directory and change to https://github.com/BangL/subhook.git
