### ISSUE TITLE
Stuck During VM Image Preparation with launch-qemu.sh

### ISSUE THREAD

**Issue by n7koirala** [AMDESE/AMDSEV#252]
Hello! I am encountering an issue while preparing the VM image following the guide provided here: [Prepare VM Image](https://github.com/AMDESE/AMDSEV?tab=readme-ov-file#prepare-vm-image-4). 

I am using the `snp-latest` branch from this repository: [AMDSEV](https://github.com/AMDESE/AMDSEV/tree/snp-latest).

After running the `launch-qemu.sh` script with the correct `.qcow2` file and `.iso` file, the process hangs indefinitely. I am attaching a screenshot showing the point where it gets stuck.
<img width="1444" alt="launch_script" src="https://github.com/user-attachments/assets/15f95a1e-cbd3-4f0d-8a55-45b6b9f858c5">

## Steps to Reproduce

1. Follow the instructions for building and preparing the VM from the `snp-latest` branch.
2. Run the `launch-qemu.sh` script with the following arguments:
   ```bash
   ./launch-qemu.sh -hda <qcow_file> -cdrom <iso_file> 

I appreciate any help in advance! Thank you.

**Comment by tlendacky** [comment]
When you get to the grub prompt, you need to edit the install entry and add "console=ttyS0,115200n8" to the kernel command line.

**Comment by n7koirala** [comment]
Could you please clarify? I do not get any grub prompt after running the launch script with the qcow file and iso file. The process seems to hang during the boot process, and I cannot access or modify the grub entries.

**Comment by tlendacky** [comment]
The process isn't hung, it is just not using the serial port for display so you can't see the current state of the boot/installation. What ISO are you using?

The output indicates that the ISO is being used for booting. I'm surprised you don't get to a grub prompt. Usually, installation ISOs will boot to grub and give you some boot options to choose from.

**Comment by n7koirala** [comment]
Okay, that makes sense, I'm running it on a remote server. I have tried ISOs for both Ubuntu 18.04.6 and Ubuntu 20.04.6. I never get to the point where the VM image can take input from the grub. Do you know what I might be missing here?

**Comment by tlendacky** [comment]
It looks like the grub menu doesn't come up before 22.04 (I didn't try anything between 20.04 and 22.04). So, if you move to a newer release of Ubuntu, you should be ok.

Otherwise, if you have to use one of the older versions, use a method other than the launch-qemu.sh script to initially install the image.

**Comment by n7koirala** [comment]
Thank you! Using a newer release of Ubuntu (24.04) fixed that issue, and I'm able to see the grub menu and several options: 
<img width="759" alt="Screenshot 2024-12-05 at 9 53 51 PM" src="https://github.com/user-attachments/assets/09239550-8923-4822-be7e-00122fc90a3b">

Trying to install the server, however, makes the process hang again in the same memory setup process:
<img width="784" alt="Screenshot 2024-12-05 at 9 57 22 PM" src="https://github.com/user-attachments/assets/2ab564b2-50d9-4b26-ab96-2d36221a580b">

Is there any way I can access the kernel command line and edit the install entry like you mentioned above?

**Comment by tlendacky** [comment]
When you get to the grub prompt and the "Try and Install Ubuntu Server" is highlighted, press the 'e' key to edit the entry contents. Use the cursor and find the line that starts with "linux" and add the previously mentioned parameters to the end of the line.

**Comment by n7koirala** [comment]
That worked. Thank you so much! I'll close this issue.
