### ISSUE TITLE
Enabling Debug Mode on SEV-SNP supported CPU

### ISSUE THREAD

**Issue by AlexOrozco1256** [AMDESE/AMDSEV#256]
Hello,

I am trying to enable debug mode on my guest, but I can't find any instructions or settings in my BIOS for enabling debug mode on the host.

Are there any additional steps I need to take besides setting the debug bit in the guest policy to enable debugging a guest CVM.

Thanks,

Alex

**Comment by Freax13** [comment]
Debug mode is not a system-wide setting, so there's no BIOS option. Setting the debug bit in the guest policy should be sufficient.

**Comment by AlexOrozco1256** [comment]
I was able to figure it out, I setup my policy incorrectly (forgot to set the reserved bit 17). Thanks for the fast response @Freax13!
