### ISSUE TITLE
Unable to launch SEV Guest

### ISSUE THREAD

**Issue by qw0b** [AMDESE/AMDSEV#36]
Hi SEV Team,

when I try to start an SEV Guest with
```
/usr/local/bin/qemu-system-x86_64 -enable-kvm -cpu EPYC -machine q35 -smp 1,maxcpus=64 -m 4096M,slots=5,maxmem=30G -drive if=pflash,format=raw,unit=0,file=/usr/local/share/qemu/OVMF_CODE.fd,readonly -drive if=pflash,format=raw,unit=1,file=OVMF_VARS.fd -drive file=ubuntu-18.04.3-desktop-amd64.iso,media=cdrom -boot d -netdev user,id=vmnic -device e1000,netdev=vmnic,romfile= -drive file=ubuntu-18.04.qcow2,if=none,id=disk0,format=qcow2 -device virtio-scsi-pci,id=scsi,disable-legacy=on,iommu_platform=true -device scsi-hd,drive=disk0 -object sev-guest,id=sev0,cbitpos=47,reduced-phys-bits=1 -machine memory-encryption=sev0 -nographic -vnc :0 -monitor pty -device virtio-rng-pci,disable-legacy=on,iommu_platform=true
```

it always yield the follwing error:

```
qemu-system-x86_64: sev_guest_init: failed to initialize ret=-25 fw_error=0 ''
qemu-system-x86_64: failed to initialize KVM: Operation not permitted
```
I followed the instructions from the README, but used ubuntu 19.04 instead of 18.04 ( In Ubuntu 18.04 dmesg always contained: ccp 0000:05:00.2: SEV: failed to INIT error 0x8003 ).
I am using an AMD EPYC 3151 Processor.
The ccp Module outputs the following to dmesg:
```
[    3.947262] ccp 0000:05:00.2: enabling device (0000 -> 0002)
[    3.949480] ccp 0000:05:00.2: ccp enabled
[    3.949533] ccp 0000:05:00.2: psp enabled
[    3.949534] ccp 0000:05:00.2: enabled
[    3.949959] ccp 0000:06:00.1: enabling device (0000 -> 0002)
[    3.950477] ccp 0000:06:00.1: ccp enabled
[    3.950478] ccp 0000:06:00.1: enabled
[    3.970342] ccp 0000:05:00.2: SEV firmware update successful
[    3.991709] ccp 0000:05:00.2: SEV API:0.17 build:11
```

I tried tracing the error message in the kernel.  It seems to originate from https://elixir.bootlin.com/linux/v4.20/source/arch/x86/kvm/svm.c#L6916.
Furthermore I noticed, that i cannot set the sev parameter of the kvm_amd module to 1.
I traced this to https://elixir.bootlin.com/linux/v5.2.9/source/arch/x86/kvm/svm.c#L1337. By adding some debug statements I found out, that the check "boot_cpu_has(X86_FEATURE_SEV)" in this function returns false, which seems to disable the sev feature in kvm.

**Comment by tlendacky** [comment]
If boot_cpu_has(X86_FEATURE_SEV) is returning false, it is being disabled here: https://elixir.bootlin.com/linux/v5.2.9/source/arch/x86/kernel/cpu/amd.c#L594.

Paste the output of "cpuid -r -1 -l 0x8000001f", "rdmsr -x 0xc0010010" and "rdmsr -x 0xc0010015".

**Comment by qw0b** [comment]
Hi,
I get the following results

cpuid -r -1 -l 0x8000001f  
```
CPU: 0x8000001f 0x00: eax=0x0000000f ebx=0x0000016f ecx=0x0000000f edx=0x00000001
```
rdmsr -x 0xc0010010
```
740000
```
rdmsr -x 0xc0010015
```
9000011
```

**Comment by tlendacky** [comment]
MSR 0xc0010010, 0x740000 => Bit 23 is zero, memory encryption features are disabled.

You might want to see if there is a BIOS option available that would enable this.

**Comment by qw0b** [comment]
There is no such option in my BIOS. I'm using the following Board from Supermicro: https://www.supermicro.com/en/products/motherboard/M11SDV-4C-LN4F . Is the BIOS the only way to set this bit?

**Comment by tlendacky** [comment]
I don't know, I've never tried doing it.

**Comment by qw0b** [comment]
I patched https://elixir.bootlin.com/linux/v5.2.9/source/arch/x86/kernel/cpu/amd.c#L594 , to activerly set Bit 23 in MSR 0xc0010010. Afterwards i was able to start SEV Guests.

**Comment by tlendacky** [comment]
Good to know and glad you were able to launch SEV guests. You should still push on SuperMicro to supply a BIOS option to enable the memory encryption support so that you don't need to patch the kernel.

**Comment by khushboo-dfn** [comment]
hi @qw0b , did you find out what setting in SuperMicro BIOS needs to be enabled. I am running into the same issue.

**Comment by its-luca** [comment]
@khushboo-dfn 
Bios version 1.0b and upwards are supposed to have this option. However, I did never test them as the software workaround fulfilled my needs.
