### ISSUE TITLE
SEV guest stuck while loading CDROM

### ISSUE THREAD

**Issue by adilahmad17** [AMDESE/AMDSEV#38]
Hi, 

I am trying to install an SEV guest from an Ubuntu 18.04.3 host. The build scripts for
SEV (provided in the repo), work correctly and I am running the AMD kernel:

`4.20.0-sev #1 SMP Wed Oct 16 20:03:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

However, when I attempt to create a guest using the command:

`launch-qemu.sh -cdrom ubuntu-18.04-live.iso -hda ubuntu-18.04.qcow2 -console serial`

The VM first loads onto the UEFI shell from where I use the menu to load the CDROM. Then,
it is simply stuck at:

```
SmmInstallProtocolInterface: 296EB418-C4C8-4E05-AB59-39E8AF56F00A 0
CpuDxe: 5-Level Paging = 0
MpInitChangeApLoopCallback() done!
SetUefiImageMemoryAttributes - 0x000000007EBC4000 - 0x0000000000006000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007EBBE000 - 0x0000000000006000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007EBB8000 - 0x0000000000006000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007EBB2000 - 0x0000000000006000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007EBAB000 - 0x0000000000007000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007EBA2000 - 0x0000000000009000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007EB9B000 - 0x0000000000007000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007DAE1000 - 0x0000000000007000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007DA82000 - 0x0000000000005000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x000000007DA78000 - 0x0000000000005000 (0x0000000000000008)

```
I tried the same with the `-nosev` option as well but the same result shows up.
I have tested the live iso that I am using on another custom qemu machine and
it works fine so the iso isn't the issue.

Any ideas on fixing this issue would be greatly appreciated! 

Thanks!
Adil

**Comment by codomania** [comment]
By default Ubuntu installers works in graphics mode. Either you modify the kernel cmdline to force installer to use the serial console or use the VNC for the installation.

**Comment by adilahmad17** [comment]
Thanks for the reply! I will try to install some other distro with text-based installer in that case.

**Comment by lilienbm** [comment]
Hi, is this issue solved? Can we close the ticket?

**Comment by adilahmad17** [comment]
Hey, yes! Sorry for not closing it earlier. Thanks again!
