### ISSUE TITLE
Error when boot a SEV-ES machine

### ISSUE THREAD

**Issue by seedingdream** [AMDESE/AMDSEV#41]
Hi, I met some problems when boot a SEV-ES machine.
The version I used for OVMF is sev-es-v8
The kernel is sev-es-5.1-v7
and the qemu is sev-es-v2.
I am able to get and install both OVMF and QEMU successfully and I am able to get a kernel .deb files for both host and guest, whose name are 5.1.0-sev-es-guest and 5.1.0-sev-es-host.
I install the guest VM under non-sev mode and dpkg -I those guest deb files 5.1.0-sev-es-guest.
However, when I use ./launch-qemu.sh -hda <IMAGE_NAME>.qcow2 -vnc 1 -console serial -sev-es to launch a SEV-ES VM.
I always faces the error: 
qemu-system-x86_64: sev_guest_init: using :KVM_SEV_ES_INIT
qemu-system-x86_64: sev_launch_update_vmsa: LAUNCH_UPDATE_VMSA ret = -5 fw_error=3 2774 'unknown error'/
I wonder whether the branch for sev-es is currently a workable version or am I doing something wrong. 
Any suggestions are welcomed.

More info for ref:
cpuid 0x8000001f =>
eax = 0x0000000f, ebx= 0x16f, ecx = 0xf, edx= 0x5;

**Comment by seedingdream** [comment]
BTW, I am able to run a SEV VM well

**Comment by seedingdream** [comment]
My CPU is epyc 7251. I know it is the 7001 epyc series. Are there some restrictions for SEV-ES for this series?

**Comment by tlendacky** [comment]
What version of the firmware are you running? (dmesg | grep SEV)

**Comment by seedingdream** [comment]
ccp 0000:01:00.2: SEV API 0.16 build:5
SVM: SEV supported:11 ASIDs
SVM: SEV-ES supported: 4 ASIDs

**Comment by tlendacky** [comment]
You probably need to upgrade your SEV firmware - but you need 0.16 build:12 in order to do that without updating your BIOS.

Can you check if there is a new BIOS available for your system?

**Comment by seedingdream** [comment]
Thank you for your reply. This is the BIOS available for my motherboard. 
https://www.gigabyte.com/us/Server-Motherboard/MZ31-AR0-rev-1x/support#support-dl-bios
And the current bios version is F07.
However, I don't find there are some BIOS update related to SEV/SEV-ES
May I ask how to upgrade the SEV firmware and update the current 0.16-build5 to build-16.
Can I get the new build somewhere?

**Comment by tlendacky** [comment]
The SEV firmware is part of the BIOS and the release notes may not explicitly call out a version change. If you're at F07 and F13 is available, give it a try and see if you then have a later SEV firmware build (it is a different AGESA PI level).

**Comment by seedingdream** [comment]
I found there are some BIOS update for motherboard which support both 7001 and 7002 series. Will  the BIOS which supports 7002 series always be a SEV-ES capable version?

Moreover, I wonder why the build-5 version is a "unworkable" version, are there some big updates in SEV-ES? The error I faced seems like you are making some big changes (interface&workflow level) here.

**Comment by tlendacky** [comment]
Yes, EPYC firmware is SEV/SEV-ES capable.

There were bugs that were found that needed to be fixed and you could be hitting one. If upgrading your BIOS brings you to 0.16 build:12 or higher then you will be able to successfully update your SEV firmware whenever a new version comes out without upgrading your BIOS. The ccp/psp driver will search for a file in /lib/firmware/amd.  If your distro doesn't have the latest version installed, you can get it at https://developer.amd.com/sev/.

**Comment by seedingdream** [comment]
OK. Last question here. I will close the issue afterward. 
Do you know a motherboard & cpu combo in the market which is able to run a SEV-ES machine?
Actually I have bought two server, one's motherboard is supermicro and anthoer is gigabyte. Neither can run a SEV-ES instance. Do you have any idea which combo in the market supports SEV-ES?
I also notice there is a new feature called sev-snp.
Will the machine which supports SEV-ES also support SEV-SNP?

**Comment by tlendacky** [comment]
Have you upgraded the BIOS of your machine and tested it?  Please do that and you'll likely have a machine that can run SEV-ES.  Please do that and then post the same dmesg | grep SEV as previous.

I don't have the information to answer your question concerning OEM systems. You will need to follow up with the OEM.

SEV-SNP is part of future hardware. I can't answer what the OEMs will do in regards to support of future hardware.

**Comment by seedingdream** [comment]
I tried to update bios in both supermicro and gigabyte. 
For supermicro, there is no SEV-ES ASID setting in bios even with the newest bios version.
For gigabyte, I update to F13 and after that I repeat all the steps and now when I use dmesg| grep SEV.
I can get
ccp 0000:01:00.2: SEV API 0.16 build:12 
SVM: SEV supported:11 ASIDs
SVM: SEV-ES supported: 4 ASIDs
and the cpuid 0x8000001f shows:
eax = 0x0000000f, ebx= 0x16f, ecx = 0xf, edx= 0x5;
Yeah, everything looks perfectly.
I install the guest VM under non-sev mode and dpkg -I those guest deb files 5.1.0-sev-es-guest.
However, when I tried to launch it as a sev-es VM,
The same error shows again:
qemu-system-x86_64: sev_guest_init: using :KVM_SEV_ES_INIT
qemu-system-x86_64: sev_launch_update_vmsa: LAUNCH_UPDATE_VMSA ret = -5 fw_error=3 2774 'unknown error'/

After that, I boot the VM with only sev and check its kernel version. The kernel version is the 5.1.0-sev-es-guest. It seems it can work pretty well under SEV mode but not sev-es mode.

Do you have any suggestions?
Do you think this is because my cpu is 7001 series but not 7002 series.

Thanks a lot

**Comment by tlendacky** [comment]
Yes, so I recommend pulling down the SEV firmware located at https://developer.amd.com/sev. Look for the link amd_sev_fam17h_model0xh_0.17b22.zip.  Unzip the file and copy amd_sev_fam17h_model0xh_0.17b22.sbin to /lib/firmware/amd/amd_sev_fam17h_model0xh.sbin (the name must be this in order for the ccp/psp driver to find the file). This will upgrade the SEV firmware on each boot from 0.16 build:12 to 0.17 build:22.  Reboot to the 5.1.0-sev-es-host kernel, verify that the new firmware loaded and then retry your test.

**Comment by seedingdream** [comment]
I cannot find the /lib/firmware/amd/   folder, Is this OK? I will create a new one.

**Comment by tlendacky** [comment]
Do you have the /lib/firmware/ directory?  If yes, it is okay to create the amd folder.  If not, I'm not sure where firmware files live on your system but you can still try creating /lib/firmware/amd/.

**Comment by seedingdream** [comment]
I have the /lib/firmware directory but when I use ls| grep amd.
I can only find amdgpu and amd-ucode. SO I creat the amd folder here and copy the file to this folder as well as change its name 

/lib/firmware/amd$ ls
amd_sev_fam17h_model0xh.sbin

After that I reboot the machine, and when I use dmesg| grep sev again:

[    0.000000] Linux version 5.1.0-sev-es-host (root@melody-MZ31-AR0-00) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #1 SMP Tue Jan 14 16:59:11 PST 2020
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-5.1.0-sev-es-host root=UUID=30c61858-1ad3-435b-96cc-d50e396cc0af ro quiet splash vt.handoff=1
[    0.000000] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.1.0-sev-es-host root=UUID=30c61858-1ad3-435b-96cc-d50e396cc0af ro quiet splash vt.handoff=1
[    1.692821] usb usb1: Manufacturer: Linux 5.1.0-sev-es-host xhci-hcd
[    1.693255] usb usb2: Manufacturer: Linux 5.1.0-sev-es-host xhci-hcd
[    1.694047] usb usb3: Manufacturer: Linux 5.1.0-sev-es-host xhci-hcd
[    1.694282] usb usb4: Manufacturer: Linux 5.1.0-sev-es-host xhci-hcd

Is this the result what we expected?

**Comment by seedingdream** [comment]
I have the /lib/firmware directory but when I use ls| grep amd.
I can only find amdgpu and amd-ucode. SO I creat the amd folder here and copy the file to this folder as well as change its name

/lib/firmware/amd$ ls
amd_sev_fam17h_model0xh.sbin

After that I reboot the machine, and when I use dmesg| grep sev again:

[ 0.000000] Linux version 5.1.0-sev-es-host (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #1 SMP Tue Jan 14 16:59:11 PST 2020
[ 0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-5.1.0-sev-es-host root=UUID=30c61858-1ad3-435b-96cc-d50e396cc0af ro quiet splash vt.handoff=1
[ 0.000000] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.1.0-sev-es-host root=UUID=30c61858-1ad3-435b-96cc-d50e396cc0af ro quiet splash vt.handoff=1
[ 1.692821] usb usb1: Manufacturer: Linux 5.1.0-sev-es-host xhci-hcd
[ 1.693255] usb usb2: Manufacturer: Linux 5.1.0-sev-es-host xhci-hcd
[ 1.694047] usb usb3: Manufacturer: Linux 5.1.0-sev-es-host xhci-hcd
[ 1.694282] usb usb4: Manufacturer: Linux 5.1.0-sev-es-host xhci-hcd

Is this the result what we expected?

**Comment by tlendacky** [comment]
Can you do dmesg | grep SEV so I can see the firmware level to be sure the new one loaded?

**Comment by seedingdream** [comment]
Sorry I use the small letters. 
[    3.980822] ccp 0000:01:00.2: SEV firmware update successful
[    4.028038] ccp 0000:01:00.2: SEV API:0.17 build:22
[    4.641120] SVM: SEV supported: 11 ASIDs
[    4.641121] SVM: SEV-ES supported: 4 ASIDs

I will have another try here

**Comment by tlendacky** [comment]
Ok, the firmware loaded and you are now at 0.17 build:22.  Try the SEV-ES test again.

**Comment by tlendacky** [comment]
Btw, the latest versions of the code are:
 qemu => sev-es-v3
 ovmf => sev-es-v9
 kernel => sev-es-5.1-v7

It's important that you be at the latest of each, since there are dependencies between at different levels.

**Comment by seedingdream** [comment]
Thanks so much. It seems I can launch a sev-es guest now! I will close this issue now.

**Comment by tlendacky** [comment]
Good to hear it's working.
