### ISSUE TITLE
Unable to launch VM with SEV-ES enabled

### ISSUE THREAD

**Issue by morbitzer** [AMDESE/AMDSEV#45]
Hey, 
Unfortunately, I am not able to launch a SEV-ES VM. 

In the host, everything is looking good: 
`sudo dmesg | grep SEV`
`[    3.696228] ccp 0000:04:00.2: SEV firmware update successful`
`[    3.732363] ccp 0000:04:00.2: SEV API:0.17 build:22`
`[    4.067938] SVM: SEV supported: 12 ASIDs`
`[    4.067940] SVM: SEV-ES supported: 3 ASIDs`

CPUID is also looking good: 
`cpuid -l 0x8000001f -r`
`CPU 0:`
`   0x8000001f 0x00: eax=0x0000000f ebx=0x0000016f ecx=0x0000000f edx=0x00000004`
[...]
`CPU 15:`
`   0x8000001f 0x00: eax=0x0000000f ebx=0x0000016f ecx=0x0000000f edx=0x00000004`

I created a clean qcow2 image and installed ubuntu server on it. 
Afterwards, I installed the same kernel in the VM as on the host. 

When I launch the VM without SEV/SEV-ES, everything works as expected. 

Also with the switch `-sev`, everything seems to work: 
`launch-qemu.sh -hda ubuntu-es.qcow2 -sev`
In the guest, I get the output: 
` sudo dmesg | grep SEV`
`[    0.148452] AMD Secure Encrypted Virtualization (SEV) active`

However, when I use the `-sev-es` switch, I am getting errors:
`PciSioSerial: Create SIO child serial device - Device Error` 
`!!!! Find image based on IP(0x7DDC89BB) 1af41000.efidrv (ImageBase=000000007DDB4000, EntryPoint=000000007DDBA1EC) !!!!`

I attached the [stdout.log](https://github.com/AMDESE/AMDSEV/files/4635414/stdout.log) for the details. 

Any idea what's going wrong? 
I already tried different VM images, but none of them seem to work. 
Also tried to use a fresh version of the `OVMF_VARS.fd`. 

As far as I understand, the error is already happening at the EFI stage.

**Comment by tlendacky** [comment]
Those same errors are present in non SEV-ES guests as well.

I'm not sure what could be going wrong.  What branches of the repo are you using (qemu, ovmf and linux)?

**Comment by morbitzer** [comment]
I used the `build.sh` script, so the branches are the one from the script. To be specific: 
qemu: `sev-es-v6`
ovmf: `sev-es-v14`
linux: `sev-es-5.6-v3`

I re-build everything today, so they should all be up to date.

**Comment by tlendacky** [comment]
There are newer versions available, I just haven't updated the build file to pick them up yet. Try these versions and see if they work:
qemu: sev-es-v7
ovmf: sev-es-v15
linux: sev-es-5.7-v1

Also, what is your base distro and version that you're running for the hypervisor and for the guest?

**Comment by morbitzer** [comment]
I tried with the new branches.
(Please note that I had to execute `git submodule update --init --recursive` in the qemu directory in order for ovmf to build. Otherwise, there would be missing files from `brotli`.)

I also updated my gcc. Originally, I was using `gcc-7`, now I'm trying with `gcc-9`. 

Unfortunately, I'm still having the same problem. 
[stdout.log](https://github.com/AMDESE/AMDSEV/files/4643015/stdout.log) attached. 

I am running Debian 11 on the host. For the guest, I was trying to install Ubuntu 18.04 Server.

Are there any specific kernel options I have to enable/disable? For example, I noticed that the launch-script requires `CONFIG_X86_CPUID`, which I didn't have originally in my kernel. Could you provide a kernel config that works for you?

**Comment by tlendacky** [comment]
Comparing your log to mine, I notice that you have the following in yours (and what appears to be causing the #UD).  What does the 1af41000.efi driver do anyway? Any information you can provide about it?

-Select Item: 0x2C^M
-[Security] 3rd party image[7EE61F18] can be loaded after EndOfDxe: PciRoot(0x0)/Pci(0x2,0x0)/Offset(0x10E00,0x24FFF).^M
-InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 7EE241C0^M
-Loading driver at 0x0007DE69000 EntryPoint=0x0007DE6E327 1af41000.efi^M
-InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 7EE20D18^M
-ProtectUefiImageCommon - 0x7EE241C0^M
-  - 0x000000007DE69000 - 0x00000000000A0320^M
-Image type IA32 can't be started on X64 UEFI system.^M
-[Security] 3rd party image[7EE61F28] can be loaded after EndOfDxe: PciRoot(0x0)/Pci(0x2,0x0)/Offset(0x25000,0x3B3FF).^M
-InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 7EE20040^M
-Loading driver at 0x0007DDC2000 EntryPoint=0x0007DDC81EC 1af41000.efi^M
-InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 7EE70018^M
-ProtectUefiImageCommon - 0x7EE20040^M
-  - 0x000000007DDC2000 - 0x00000000000A68C0^M
-InstallProtocolInterface: 18A031AB-B443-4D1A-A5C0-0C09261E9F71 7DDE5930^M
-InstallProtocolInterface: 6A7A5CFF-E8D9-4F70-BADA-75AB3025CE14 7DDE5900^M

**Comment by tlendacky** [comment]
Ah, turns out the 1af41000.efi driver is the iPXE UEFI option ROM for the virtio-net NIC. I see you are missing "romfile=" from your command line entry for -device virtio-net-pci.  Tack "romfile=" to end of the virtio-net-pci entry and see if that resolves it.

**Comment by morbitzer** [comment]
Yes, I used virtio to be able to connect to the VM. I didn't understand that this was the issue. 
I can start the VM now with the `-sev-es` switch, thanks for your help!

Within the VM, I get the following output: 
`sudo dmesg | grep SEV`
`[    0.150023] AMD Secure Encrypted Virtualization (SEV) active`

I do not see anything about SEV-ES. 

However, `sudo rdmsr -a 0xc0010131` returns `3`, so `11` in binary. So from what I understand this tells me that SEV and SEV-ES are active, despite there being no output like `AMD Secure Encrypted Virtualization - Encrypted State (SEV-ES) active` in dmesg?

**Comment by tlendacky** [comment]
> Yes, I used virtio to be able to connect to the VM. I didn't understand that this was the issue.
> I can start the VM now with the `-sev-es` switch, thanks for your help!

Good to hear.

> 
> Within the VM, I get the following output:
> `sudo dmesg | grep SEV`
> `[ 0.150023] AMD Secure Encrypted Virtualization (SEV) active`
> 
> I do not see anything about SEV-ES.
> 
> However, `sudo rdmsr -a 0xc0010131` returns `3`, so `11` in binary. So from what I understand this tells me that SEV and SEV-ES are active, despite there being no output like `AMD Secure Encrypted Virtualization - Encrypted State (SEV-ES) active` in dmesg?

I incorporated the guest support that was submitted upstream and, depending on the that version, mayb be missing the updated message. But as you see from the MSR, you are running with SEV-ES active. If you use the sev-es-5.7-v1 branch in the guest, you'll get an SEV-ES related message (the format has been changed to report SEV features: AMD Memory Encryption Features active: SEV SEV-ES).

**Comment by morbitzer** [comment]
I checked with the `sev-es-5.7-v1` branch, and indeed, there is the message. 
Closing the issue, thanks for your help!
