### ISSUE TITLE
Why 'no-reboot' option in SEV-ES script?

### ISSUE THREAD

**Issue by martinradev** [AMDESE/AMDSEV#47]
Hello all,

I am curious why there is the 'no-reboot' option in the SEV-ES qemu launch script:
https://github.com/AMDESE/AMDSEV/blob/sev-es/launch-qemu.sh

**Comment by tlendacky** [comment]
Reboot via reset isn't supported. Since a reboot via reset is done by resetting the vCPU registers from the VMM, the VMRUN will fail since the guest registers are altered outside of the guest.

**Comment by martinradev** [comment]
Thanks, closing.
