### ISSUE TITLE
Attestation of the VM launched with SEV

### ISSUE THREAD

**Issue by nicopal** [AMDESE/AMDSEV#49]
The project is a collection of scripts to _launch_ an SEV-enabled VM. However, it remains unclear what is the attestation protocol. Has it been implemented? Without attestation, launching a VM with SEV on a remote machine does not add any additional security guarantees.

In a nutshell: is there an implementation of the attestation protocol?

**Comment by lilienbm** [comment]
Yes, it can be found in the SEV API spec (Secure Encrypted Virtualization API) on https://developer.amd.com/sev/

**Comment by jpecholt** [comment]
@nicopal 
QEMU provides a means to obtain the launch measure of a VM which was previously calculated by the SEV firmware. See the QMP monitor and the [query-sev-launch-measure](https://qemu.readthedocs.io/en/latest/interop/qemu-qmp-ref.html#qapidoc-2505) command for reference. Note that the VM must be started with SEV support, the desired guest policy, launch blob, GODH and a QMP socket. Using the [SEV-tool](https://github.com/AMDESE/sev-tool) and its `calculate_measurement` command, you can compute the expected launch measure and compare the provided with the expected one.

When you want to inject a secret (e.g. a disk encryption passphrase) into the VM, the corresponding UEFI/bootloader must be capable of reading it out and actually use it, thus a custom image is required. This is more complex and involves the EDK II project/OVMF and grub patches. [This article](https://blog.hansenpartnership.com/deploying-encrypted-images-for-confidential-computing/) is a good reference.
