### ISSUE TITLE
Software support for full disk encryption

### ISSUE THREAD

**Issue by jtorr547** [AMDESE/AMDSEV#52]
Hi,

   I am trying to figure out, how to setup an SEV-ES VM running a Linux guest that has fully encrypted (virtual) disks.

   However, I am struggling on passing the disk encryption key to the VM.
   According to the SEV-API, the LAUNCH_SECRET command can be used to securely transfer secrets from the guest owner to (guest) physical address belonging to the encrypted memory
   of the VM. So, to my understanding, the next step would be to get the encryption system to read the key from memory. This is the point where I am struggling, as
   in the standard disk encryption setup, the key would either be read interactively or from a keyfile.
   Is there any software support for reading it from a (predefined) memory location or is there some other kind of workflow/mechanism that I could use to achieve this?

   I hope this makes sense.

**Comment by codomania** [comment]
I am not aware of existing software stack reading the key from the fixed memory location, but I assume that you may able to modify those software's to read the key from the predefined address or you can have a separate tool which reads the data from the fixed location and saves in a keyfile which can be used later.

**Comment by jtorr547** [comment]
Thanks for the answer!
