### ISSUE TITLE
Missing /lib/modules/5.10.0-rc1-sev-es+

### ISSUE THREAD

**Issue by Alexandre-Neves** [AMDESE/AMDSEV#57]
I've been trying to boot into the sev-es-v3 kernel and I'm getting the following message while booting into that kernel:

`mdadm: No device listed in conf file were found.`

I then booted back into a working kernel (5.4.63.1) and tried running build.sh one more time, no errors or warnings reported.

Then I ran `update-initramfs -u`, which yielded the following:

`update-initramfs: Generating /boot/initrd.img-5.10.0-rc1-sev-es+
W: missing /lib/modules/5.10.0-rc1-sev-es+
W: Ensure all necessary drivers are built into the linux image!
depmod: ERROR: could not open directory /lib/modules/5.10.0-rc1-sev-es+: No such file or directory
depmod: FATAL: could not search modules: No such file or directory
cat: /var/tmp/mkinitramfs_hJNrHa/lib/modules/5.10.0-rc1-sev-es+/modules.builtin: No such file or directory
find: ‘/var/tmp/mkinitramfs_hJNrHa/lib/modules/5.10.0-rc1-sev-es+/kernel’: No such file or directory
cryptsetup: WARNING: The initramfs image may not contain cryptsetup binaries 
    nor crypto modules. If that's on purpose, you may want to uninstall the 
    'cryptsetup-initramfs' package in order to disable the cryptsetup initramfs 
    integration and avoid this warning.
depmod: WARNING: could not open modules.order at /var/tmp/mkinitramfs_hJNrHa/lib/modules/5.10.0-rc1-sev-es+: No such file or directory
depmod: WARNING: could not open modules.builtin at /var/tmp/mkinitramfs_hJNrHa/lib/modules/5.10.0-rc1-sev-es+: No such file or directory
update-initramfs: Generating /boot/initrd.img-5.10.0-rc1-sev-es
W: missing /lib/modules/5.10.0-rc1-sev-es
W: Ensure all necessary drivers are built into the linux image!
depmod: ERROR: could not open directory /lib/modules/5.10.0-rc1-sev-es: No such file or directory
depmod: FATAL: could not search modules: No such file or directory
cat: /var/tmp/mkinitramfs_QeSkQ0/lib/modules/5.10.0-rc1-sev-es/modules.builtin: No such file or directory
find: ‘/var/tmp/mkinitramfs_QeSkQ0/lib/modules/5.10.0-rc1-sev-es/kernel’: No such file or directory
cryptsetup: WARNING: The initramfs image may not contain cryptsetup binaries 
    nor crypto modules. If that's on purpose, you may want to uninstall the 
    'cryptsetup-initramfs' package in order to disable the cryptsetup initramfs 
    integration and avoid this warning.
depmod: WARNING: could not open modules.order at /var/tmp/mkinitramfs_QeSkQ0/lib/modules/5.10.0-rc1-sev-es: No such file or directory
depmod: WARNING: could not open modules.builtin at /var/tmp/mkinitramfs_QeSkQ0/lib/modules/5.10.0-rc1-sev-es: No such file or directory
update-initramfs: Generating /boot/initrd.img-5.4.65.1.amd64-smp
cryptsetup: WARNING: The initramfs image may not contain cryptsetup binaries 
    nor crypto modules. If that's on purpose, you may want to uninstall the 
    'cryptsetup-initramfs' package in order to disable the cryptsetup initramfs 
    integration and avoid this warning.`

It appears that the fact that `/lib/modules/5.10.0-rc1-sev-es+` being missing is the main problem here. What could be causing this?

**Comment by tlendacky** [comment]
Not sure why that would have happened. Did you use the build script from the sev-es branch of the AMDSEV repo to build the kernel? The script will build an rpm or deb package that when installed should populate /lib/modules/.

**Comment by Alexandre-Neves** [comment]
Wait I'm on a Debian machine, how come it didn't build a Deb package (its doing rpm) ?

Yes I'm using the right branch by the way.

This Debian is custom flavored, could that be a problem?

**Comment by tlendacky** [comment]
The scripts uses "if [ "$ID_LIKE" = "debian" ]; then" to decide whether to build a deb or rpm. You can update the script to just build the deb and give that a try.

**Comment by Alexandre-Neves** [comment]
Yep, that was it! Thank you so much. Maybe either mention that on the README or add the option in the script instead of deducing whether deb or rpm should be used? Anyways, I'm closing this.
