### ISSUE TITLE
(Future) Support for nested virtualization and unencrypted VM live migration

### ISSUE THREAD

**Issue by jpecholt** [AMDESE/AMDSEV#63]
Hello,
we are currently working with your hardware (Epyc Naples processors) and are kind of testing out the limitations of SEV-encrypted VMs. Namely, we are trying to run nested VMs, with the outer VM being SEV-encrypted and the inner being a normal VM using KVM. Both host and outer VM run with the current Linux 5.11 kernel. When trying to load the kvm_amd module inside the outer VM, we receive the following message: 
`[  209.571618] SVM: KVM is unsupported when running as an SEV guest`
`[  209.572706] kvm: no hardware support`
This is a pretty clear answer that nested virtualization with KVM is not currently possible, I assume? Am I correct to conclude that this would not work either with SEV-SNP / Epyc Rome processors and their current Firmware? If so, are you planning on supporting this feature in the future?

Additionally, we are investigating live migration strategies for SEV-encrypted VMs. By looking at your API specifications (namely at SEND_START, RECEIVE_START  and the proposed live migration usage flows), we deduced that source and destination both have to be platforms capable of SEV. Are you considering to allow source platforms not capable of SEV in the future? With the correct hypervisor support, unencrypted VMs could be encrypted and migrated to the target platform capable of SEV. It would obviously require additions / modifications to your API (e.g. allow for the source platform to provide a Diffie-Hellman key similar to the GODH during launch instead of the PDH and its certificate chain only present in SEV hardware).

Both of these features, nested virtualization and VM live migration from non-SEV to SEV platform, are approaches that would allow for unencrypted VMs to be migrated to secure encrypted VMs, which is why we are interested in these features.
Cheers,
Jo

**Comment by tlendacky** [comment]
> Hello,
> we are currently working with your hardware (Epyc Naples processors) and are kind of testing out the limitations of SEV-encrypted VMs. Namely, we are trying to run nested VMs, with the outer VM being SEV-encrypted and the inner being a normal VM using KVM. Both host and outer VM run with the current Linux 5.11 kernel. When trying to load the kvm_amd module inside the outer VM, we receive the following message:
> `[ 209.571618] SVM: KVM is unsupported when running as an SEV guest`
> `[ 209.572706] kvm: no hardware support`
> This is a pretty clear answer that nested virtualization with KVM is not currently possible, I assume? Am I correct to conclude that this would not work either with SEV-SNP / Epyc Rome processors and their current Firmware? If so, are you planning on

Correct, you cannot perform nested virtualization where the L1 hypervisor is an SEV VM. This is because of the L0 hypervisor requires access to the L1 guest memory when dealing with L2 GPAs, which is encrypted and therefore can't be read.

It should be possible to have a non-SEV VM as the L1 hypervisor and then run an SEV VM as the L2 guest, but I don't believe, e.g., that KVM has that support.

> supporting this feature in the future?
> 
> Additionally, we are investigating live migration strategies for SEV-encrypted VMs. By looking at your API specifications (namely at SEND_START, RECEIVE_START and the proposed live migration usage flows), we deduced that source and destination both have to be platforms capable of SEV. Are you considering to allow source platforms not capable of SEV in the future? With the correct hypervisor support, unencrypted VMs could be encrypted and migrated to the target platform capable of SEV. It would obviously require additions / modifications to your API (e.g. allow for the source platform to provide a Diffie-Hellman key similar to the GODH during launch instead of the PDH and its certificate chain only present in SEV hardware).

I'm not sure it would be possible to do this, since you would need to somehow modify every page table in the guest to include the encryption bit (or not include it - depending on the page state needed). As of now, there aren't any plans to support that.

Thanks,
Tom

> 
> Both of these features, nested virtualization and VM live migration from non-SEV to SEV platform, are approaches that would allow for unencrypted VMs to be migrated to secure encrypted VMs, which is why we are interested in these features.
> Cheers,
> Jo

**Comment by jpecholt** [comment]
Hi Tom,
thank you for your fast reply and clearing up my questions!
Best,
Jo
