### ISSUE TITLE
Cannot boot snp guest with dracut emergency mode

### ISSUE THREAD

**Issue by haosanzi** [AMDESE/AMDSEV#79]
Hi, I have followed the steps in [link](https://github.com/AMDESE/AMDSEV/tree/sev-snp-devel), and my snp host environment is ready.

When I launch snp guest with `launch-qemu.sh`

```shell
qemu-img create -f qcow2 img.qcow2 30G
./launch-qemu.sh -hda img.qcow2 -sev-snp -kernel bzImage -initrd /boot/initramfs-5.16.0-rc4-snp-guest+.img
```

- bzImage: snp guest kernel bzImage
- initramfs-5.16.0-rc4-snp-guest+.img: snp guest initram

The detailed lauch command is
```
/root/snp/AMDSEV/snp-release-2021-12-27/usr/local/bin/qemu-system-x86_64 -enable-kvm -cpu EPYC-v4 -machine q35 -smp 4,maxcpus=64 -m 2048M,slots=5,maxmem=30G -no-reboot -drive if=pflash,format=raw,unit=0,file=/root/snp/AMDSEV/snp-release-2021-12-27/usr/local/share/qemu/OVMF_CODE.fd,readonly -netdev user,id=vmnic -device virtio-net-pci,disable-legacy=on,iommu_platform=true,netdev=vmnic,romfile= -drive file=/root/snp/AMDSEV/snp-release-2021-12-27/img.qcow2 ,if=none,id=disk0,format=qcow2 -device virtio-scsi-pci,id=scsi0,disable-legacy=on,iommu_platform=true -device scsi-hd,drive=disk0 -machine memory-encryption=sev0,vmport=off -object sev-snp-guest,id=sev0,cbitpos=51,reduced-phys-bits=1 -kernel bzImage -append console=ttyS0 earlyprintk=serial root=/dev/sda2 -initrd /boot/initramfs-5.16.0-rc4-snp-guest+.img -nographic -monitor pty -monitor unix:monitor,server,nowait
```

However, I meet the following error:
```
[  OK  ] Reached target System Initialization.
[  OK  ] Started Dispatch Password Requests to Console Directory Watch.
[  OK  ] Reached target Paths.
[  OK  ] Reached target Basic System.
[    1.510649] failover: module verification failed: signature and/or required key missing - tainting kernel
[    1.566837] virtio_net virtio0 enp0s2: renamed from eth0
[    2.070783] random: crng init done
[    2.071181] random: 7 urandom warning(s) missed due to ratelimiting
......
[  190.450586] dracut-initqueue[334]: Warning: dracut-initqueue timeout - starting timeout scripts
[  190.451729] dracut-initqueue[334]: Warning: Could not boot.
         Starting Setup Virtual Console...
[  OK  ] Started Setup Virtual Console.
         Starting Dracut Emergency Shell...
Warning: /dev/sda2 does not exist

Generating "/run/initramfs/rdsosreport.txt"


Entering emergency mode. Exit the shell to continue.
Type "journalctl" to view system logs.
You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot
after mounting them and attach it to a bug report.


dracut:/#
```

Any help will be appreciated! Thank you very much!

**Comment by tlendacky** [comment]
Usually emergency mode is entered when the initrd can't find the root filesystem. I have found, that unless I build the initrd within the guest, it ends up missing some of the virtio modules that are needed by the guest. Can you provide the full serial console output?

**Comment by haosanzi** [comment]
Thank you very much for your reply.

[snp-log.docx](https://github.com/AMDESE/AMDSEV/files/7901981/snp-log.docx) is the log file.

Can you provide a working initrd and kernel file, so that we can easily run snp guest? Thank you very much!

**Comment by tlendacky** [comment]
Yes, your initrd is definitely missing something. Your best bet is to boot the guest without SNP support through the grub menu, selecting the installation installed kernel. Then use the rpm package that was generated in the build to install it on the guest. This will generate a proper initrd.

Otherwise, you'll have to experiment with the dracut invocation on the host to include the virtualization-related modules into the initrd you're supplying on the command line.
