### ISSUE TITLE
Can SEV-SNP VM be started via libvirtd?

### ISSUE THREAD

**Issue by johnnyz2017** [AMDESE/AMDSEV#86]
Hi,

I have successfully run SEV-SNP VM with this repo, but when I try to run it via virsh I found that there is not reference xml file. So I am not sure what is the launchSecurity type and the policy etc. 

Can anyone confirm that if the SEV-SNP vm can be started via libvirtd? If so, what's the type and policy ... config is? Can anyone share one reference xml? 

Thanks in advance!

**Comment by tlendacky** [comment]
No, an SEV-SNP VM cannot be started via libvirtd, yet.

**Comment by johnnyz2017** [comment]
@tlendacky   got it, thanks!  Is there any plan to support SNP in libvirtd? Where can I find topic about it?

**Comment by johnnyz2017** [comment]
> 

Thank you!

**Comment by rrkapitz** [comment]
@tlendacky can you maybe provide more details about the missing pieces to connect the patched qemu with virsh? I assume it is not only related to the additional parameters that are necessary for qemu as virsh can passthrough parameters to qemu.

**Comment by tlendacky** [comment]
> @tlendacky can you maybe provide more details about the missing pieces to connect the patched qemu with virsh? I assume it is not only related to the additional parameters that are necessary for qemu as virsh can passthrough parameters to qemu.

I haven't looked to closely at this, so this is just a high-level thought. Right now it appears that the Qemu support will use a different object (sev-snp-guest vs sev-guest), so libvirt will have to recognize a new launch-security type and generate the new object based on that type. I'm not sure what other checks/validation would be required by libvirt.

**Comment by nicopal** [comment]
hi, trying to investigate if there has been any progress on this. Looks like by now there is support in Qemu for launching sev-snp machines. Do you know if there is ongoing work/plans on adding support for  sev-snp in libvirt?

**Comment by nicopal** [comment]
hi, trying to investigate if there has been any progress on this. Looks like by now there is support in Qemu for launching sev-snp machines. Do you know if there is ongoing work/plans on adding support for sev-snp in libvirt?

**Comment by pegahnikbakht** [comment]
Hi, does anyone have had any progress on this? Is there at least some documentation to see how qemu and libvirt need to be changed to support SEV-SNP (start the VM with virsh)?

**Comment by tlendacky** [comment]
Until the qemu interface is finalized, updates to libvirt cannot be made. There is a lot in flux with UPM and how that is to be specified on qemu as well as the new SEV-SNP security object.

**Comment by jongrimm** [comment]
FWIW, there are SUSE engineers (though I don't have their names)  looking to implement libvirt changes for SEV-SNP.   As Tom states, there are too many changes in flux with upstream Linux kernel/kvm support to predict the landing of QEMU and then libvirt changes.

**Comment by khushboo-dfn** [comment]
Hello, curious about the progress on this. Is it possible to have libvirt work with qemu?
