### ISSUE TITLE
Build kernel error

### ISSUE THREAD

**Issue by pegahnikbakht** [AMDESE/AMDSEV#87]
Hi, 

We are trying to run build.sh on ubuntu 20 with current kernel version of 5.13 but we got an error while executing this line 
"make -j `getconf _NPROCESSORS_ONLN` bindeb-pkg LOCALVERSION=-sev"

The error is as follows: 

make[2]: *** [debian/rules:7: build-arch] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[1]: *** [scripts/Makefile.package:83: bindeb-pkg] Error 2
make: *** [Makefile:1565: bindeb-pkg] Error 2

Do you have any idea why we get this error?

**Comment by pegahnikbakht** [comment]
We managed to solve this with the scripts written for Ubuntu 20, so I think I close this issue.

**Comment by eduardolfalcao** [comment]
Hello @pegahnikbakht 

I'm facing the same issue, and searched for the script fix you mentioned but couldn't find it.
In the repo there's only a directory with build for Ubuntu 18.

Could you point the location of this script fixed that you mentioned?

best regards

**Comment by pegahnikbakht** [comment]
Hi @eduardolfalcao 
Use the sev-snp-devel branch (https://github.com/AMDESE/AMDSEV/tree/sev-snp-devel) instead of master repository. There you can find scripts that were tested on Ubuntu 20.04.

Pegah
