### ISSUE TITLE
Build failure - dependency issue?

### ISSUE THREAD

**Issue by khushboo-dfn** [AMDESE/AMDSEV#94]
Hi, I am trying to build the packages for sev-snp on an Ubuntu 20.04.4 LTS machine which is not SEV-SNP enabled and am running into this failure while building the ovmf:

```
build.py...
 : error 7000: Failed to execute command
	make tbuild [/home/khushboo/AMDSEV/AMDSEV/ovmf/Build/OvmfX64/DEBUG_GCC5/X64/MdeModulePkg/Universal/Disk/RamDiskDxe/RamDiskDxe]


build.py...
 : error F002: Failed to build module
	/home/khushboo/AMDSEV/AMDSEV/ovmf/MdeModulePkg/Universal/Disk/RamDiskDxe/RamDiskDxe.inf [X64, GCC5, DEBUG]

- Failed -
Build end time: 23:11:02, May.02 2022
Build total time: 00:00:07

ERROR: nice build -q --cmd-len=64436 -DDEBUG_ON_SERIAL_PORT=TRUE -n 64 -t GCC5 -a X64 -p OvmfPkg/OvmfPkgX64.dsc

```
Is there a dependency for the binaries to be built on an SEV enabled host?
```
AMDSEV$ uname -r
5.4.0-99-generic
```

**Comment by tlendacky** [comment]
The EDK2 project has changed their build tool dependencies - specifically the NASM level on 20.04 does not meet the minimum requirements and will fail when building. But I'm not sure if this error is related. Please upgrade your NASM binary from https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/ to see if that resolves your issue.

**Comment by m1012000** [comment]
If you build 2.15.05, remove any nasm installed with apt and synlink the built folders/binaries. This will get past that error above, as of today.

**Comment by vielmetti** [comment]
Does NASM have a repo where an issue can be opened to track this too?

**Comment by tlendacky** [comment]
This isn't a NASM issue, so I don't think it should be tracked there. It is the result of EDK2 using features that are not present the version of NASM available in Ubuntu 20.04.

**Comment by vielmetti** [comment]
@tlendacky Has anyone tried this process against the now-released Ubuntu 22.04 LTS? (Maybe just to see what fails there....)

**Comment by tlendacky** [comment]
I haven't tried 22.04, yet. According to packages.ubuntu.com, they have version 2.15.05 in 22.04, so it should work. Not sure when I'll have the opportunity to try, though, so give it a shot if you want.

**Comment by khushboo-dfn** [comment]
I encountered this error again and realized that iasl needs to be installed too. Closing this issue.
